INSERT INTO `list` (`jap_name`, `eng_name`, `season`, `eps`, `stat`, `watched`) VALUES
("One Piece (1119)", "One Piece", 1, "?", "Airing", "NOT YET"),
("World Trigger 4", "World Trigger 4", 4, "?", "?", "NOT YET"),
("Gintama (19)", "Gintama", 1, 201, "Completed", "NOT YET"),
("Gintama: Shinyaku Benizakura-hen", "Gintama - The Movie", "MOVIE 1.1", 1, "Completed", "NOT YET"),
("Gintama'", "Gintama 2", 2, 51, "Completed", "NOT YET"),
("Gintama': Enchousen", "Gintama 3", 3, 13, "Completed", "NOT YET"),
("Gintama: Kanketsu-hen - Yorozuya yo Eien Nare", "Gintama: The Final Chapter - Be Forever Yorozuya", "MOVIE 3.1", 1, "Completed", "NOT YET"),
("Gintama°", "Gintama 4", 4, 51, "Completed", "NOT YET"),
("Gintama.", "Gintama 5", 5, 12, "Completed", "NOT YET"),
("Gintama.: Porori-hen", "Gintama.: Slip Arc", 6, 13, "Completed", "NOT YET"),
("Gintama.: Shirogane no Tamashii-hen", "Gintama.: Silver Soul Arc", 7, 12, "Completed", "NOT YET"),
("Gintama.: Shirogane no Tamashii-hen - Kouhan-sen", "Gintama.: Silver Soul Arc - Second Half War", 8, 14, "Completed", "NOT YET"),
("Gintama: THE SEMI-FINAL", "Gintama: THE SEMI-FINAL", 9, 2, "?", "NOT YET"),
("Soul Eater", "Soul Eater", 1, 51, "Completed", "NOT YET"),
("Soul Eater NOT!", "Soul Eater NOT!", "OVA", 12, "Completed", "NOT YET"),
("Otonari ni Ginga", "A Galaxy Next Door", 1, 12, "Completed", "NOT YET"),
("Katekyou Hitman Reborn!", "Reborn!", 1, 203, "Completed", "NOT YET"),
("3-gatsu no Lion", "March Comes in Like a Lion", 1, 22, "Completed", "NOT YET"),
("3-gatsu no Lion 2", "March Comes in Like a Lion 2", 2, 22, "Completed", "NOT YET"),
("Paprika", "Paprika", "MOVIE", 1, "Completed", "NOT YET"),
("Tsukuyomi", "Moonphase", 1, 25, "Completed", "NOT YET"),
("Freezing", "Freezing", 1, 12, "Completed", "NOT YET"),
("Freezing Vibration", "Freezing Vibration", 2, 12, "Completed", "NOT YET"),
("Platinum End", "Platinum End", 1, 24, "Completed", "NOT YET"),
("BanG Dream!", "BanG Dream!", 1, 13, "Completed", "NOT YET"),
("BanG Dream! 2", "BanG Dream! 2", 2, 13, "Completed", "NOT YET"),
("BanG Dream! 3", "BanG Dream! 3", 3, 13, "Completed", "NOT YET"),
("Nagasarete Airantou", "Nagasarete Airanto", 1, 26, "Completed", "NOT YET"),
("Koihime†Musou", "Koihime†Musou", 1, 12, "Completed", "NOT YET"),
("Shin Koihime†Musou: Otome Ryouran☆Sangokushi Engi", "Shin Koihime†Musou: Otome Ryouran☆Sangokushi Engi", 2, 12, "Completed", "NOT YET"),
("Shin Koihime†Musou: Otome Tairan", "Shin Koihime†Musou: Otome Tairan", 3, 12, "Completed", "NOT YET"),
("Reikenzan: Hoshikuzu-tachi no Utage", "Reikenzan: Hoshikuzu-tachi no Utage", 1, 12, "Completed", "NOT YET"),
("Reikenzan: Eichi e no Shikaku", "Reikenzan: Eichi e no Shikaku", 2, 12, "Completed", "NOT YET"),
("Tokyo Revengers", "Tokyo Revengers", 1, 24, "Completed", "NOT YET"),
("Tokyo Revengers 2", "Tokyo Revengers 2", 2, 13, "Completed", "NOT YET"),
("Tokyo Revengers: Tenjiku-hen", "Tokyo Revengers 3", 3, "?", "?", "NOT YET"),
("Hacka Doll: The Animation", "Hacka Doll: The Animation", 1, 13, "Completed", "NOT YET"),
("Momo Kyun Sword", "Momo Kyun Sword", 1, 12, "Completed", "NOT YET"),
("Futari wa Precure", "Pretty Cure", 1, 49, "Completed", "NOT YET"),
("Futari wa Precure: Max Heart", "Pretty Cure Max Heart", 2, 47, "Completed", "NOT YET"),
("Mushishi", "Mushi-shi", 1, 26, "Completed", "NOT YET"),
("Mushishi OVA", "Mushi-shi OVA", "OVA 1.1", 1, "Completed", "NOT YET"),
("Mushishi Zoku Shou", "Mushi-shi The Next Passage", 2, 10, "Completed", "NOT YET"),
("Mushishi Zoku Shou: Odoro no Michi", "Mushi-shi The Next Passage Special - Path of Thorns", "OVA 2.1", 1, "Completed", "NOT YET"),
("Mushishi Zoku Shou 2", "Mushi-shi The Next Passage 2", 3, 10, "Completed", "NOT YET"),
("Seikoku no Dragonar", "Dragonar Academy", 1, 12, "Completed", "NOT YET"),
("Shugo Chara!", "Shugo Chara!", 1, 51, "Completed", "NOT YET"),
("Shugo Chara!! Doki", "Shugo Chara!! Doki", 2, 51, "Completed", "NOT YET"),
("Shugo Chara! Party!", "Shugo Chara! Party!", 3, 25, "Completed", "NOT YET"),
("Taishou Otome Otogibanashi", "Taisho Otome Fairy Tale", 1, 12, "Completed", "NOT YET"),
("Onii-chan no Koto nanka Zenzen Suki Janain Dakara ne!!", "I don't like my big brother at all!!", 1, 12, "Completed", "NOT YET"),
("Zutto Mae kara Suki deshita", "I've Always Like You", 1, 1, "Completed", "NOT YET"),
("Itsudatte Bokura no Koi wa 10 cm Datta", "Our love has always been 10 centimeters apart", 3, 6, "Completed", "NOT YET"),
("Uzaki-chan wa Asobitai! 2", "Uzaki-chan Wants to Hang Out! 2", 2, 12, "Completed", "NOT YET"),
("JoJo no Kimyou na Bouken: Stone Ocean 2 (5)", "JoJo's Bizarre Adventure: Stone Ocean 2", 7, 12, "Completed", "NOT YET"),
("JoJo no Kimyou na Bouken: Stone Ocean 3", "JoJo's Bizarre Adventure: Stone Ocean 3", 8, 12, "Completed", "NOT YET"),
("Strike the Blood IV", "Strike the Blood IV", 4, 12, "Completed", "NOT YET"),
("Strike the Blood FINAL", "Strike the Blood FINAL", 5, 4, "Completed", "NOT YET"),
("Date a Live IV", "Date a Live IV", 4, 12, "Completed", "NOT YET"),
("Re:Zero kara Hajimeru Isekai Seikatsu- Season 3", "Re:Zero Starting Life in Another World- Season 3", 4, 12, "?", "NOT YET"),
("Negima!?", "Negima!? Magister Negi Magi", 2, 26, "Completed", "NOT YET"),
("Clannad: After Story", "Clannad: After Story", 2, 24, "Completed", "NOT YET"),
("Karakai Jouzu no Takagi-san", "Teasing Master Takagi-san", 3, 12, "Completed", "NOT YET"),
("UQ Holder!: Mahou Sensei Negima! 2", "UQ Holder!", 3, 12, "Completed", "NOT YET"),
("Violetever Garden Movie", "Violetever Garden: the Movie", "MOVIE 1.2", 1, "Completed", "NOT YET"),
("Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou", "Violet Evergarden: Eternity and the Auto Memory Doll", "MOVIE 1.1", 1, "Completed", "NOT YET"),
("Jashin-chan no Dropkick X", "Dropkick on My Devil!!! X", 3, 12, "Completed", "NOT YET"),
("Kaguya-sama wa Kokurasetai: Ultra Romantic", "Kaguya-sama: Love is War -Ultra Romantic-", 3, 13, "Completed", "NOT YET"),
("Kimetsu no Yaiba: Katanakaji no Sato-hen", "Demon Slayer: Swordsmith Village Arc", 4, 11, "Completed", "NOT YET"),
("Seitokai Yakuindomo Movie 2", "Seitokai Yakuindomo the Movie 2", "MOVIE 2.2", 1, "Completed", "NOT YET"),
("Gokushufudou Part 2", "The Way of the House Husband Part 2", 2, 5, "Completed", "NOT YET"),
("Gokushufudou 2", "The Way of the House Husband 2", 3, 5, "Completed", "NOT YET"),
("Rikei ga Koi ni Ochita no de Shoumei shitemita. r=1-sinθ (Heart)", "Science Fell in Love, So I Tried to Prove It r=1-sinθ", 2, 12, "Completed", "NOT YET"),
("Bungou Stray Dogs 4", "Bungou Stray Dogs 4", 4, 13, "Completed", "NOT YET"),
("Bungou Stray Dogs 5", "Bungou Stray Dogs 5", 5, 11, "AIring", "NOT YET"),
("Hello!! Kiniro Mosaic", "Hello!! Kiniro Mosaic", 2, 12, "Completed", "NOT YET"),
("Shingeki no Kyojin: The Final Season Part 2", "Attack on Titan: The Final Season Part 2", 6, 12, "Completed", "NOT YET"),
("Shingeki no Kyojin: The Final Season - Kanketsu-hen Zenpen", "Attack on Titan Final Season THE FINAL CHAPTERS Special", "OVA 6.1", 1, "Completed", "NOT YET"),
("Amanchu! -Advance-", "Amanchu! -Advance-", 2, 12, "Completed", "NOT YET"),
("Fate/Extra: Last Encore (2)", "Fate/Extra: Last Encore", 1, 10, "Completed", "NOT YET"),
("Fate/Extra: Last Encore - Irusterias Ptolemaic Theory", "Fate/Extra: Last Encore - Irusterias Ptolemaic Theory", 2, 3, "Completed", "NOT YET"),
("Fate/Grand Order: Zettai Majuu Sensen Babylonia - Initium Iter", "Fate/Grand Order: Zettai Majuu Sensen Babylonia - Initium Iter", 3, 1, "Completed", "NOT YET"),
("Fate/Grand Order: Absolute Demonic Front - Babylonia", "Fate/Grand Order Absolute Demonic Front: Babylonia", 4, 21, "Completed", "NOT YET"),
("Love Live! Nijigasaki Gakuen School Idol Doukoukai", "Love Live! Nijigasaki High School Idol Club", 1, 13, "Completed", "NOT YET"),
("Love Live! Nijigasaki Gakuen School Idol Doukoukai 2", "Love Live! Nijigasaki High School Idol Club 2", 2, 13, "Completed", "NOT YET"),
("Love Live! Nijigasaki Gakuen School Idol Doukoukai: NEXT SKY", "Love Live! Nijigasaki Gakuen School Idol Doukoukai: NEXT SKY", "OVA 2.1", 1, "Completed", "NOT YET"),
("Kyoukaisenjou no Horizon (5)", "Horizon in the Middle of Nowhere", 1, 13, "Completed", "NOT YET"),
("Kyoukaisenjou no Horizon 2", "Horizon in the Middle of Nowhere 2", 2, 13, "Completed", "NOT YET"),
("Kimi wa Kanata", "Over the Sky", "MOVIE", 1, "Completed", "NOT YET"),
("Cells At Work (Movie)", "Cells At Work (Movie)", "MOVIE", 1, "?", "NOT YET"),
("Shinsekai yori", "From the New World", 1, 25, "Completed", "NOT YET"),
("Serial Experiment Lain", "Serial Experiment Lain", 1, 13, "Completed", "NOT YET"),
("Serial Experiments Lain: The Nightmare of Fabrication", "Serial Experiments Lain: The Nightmare of Fabrication", 1, 1, "?", "NOT YET"),
("One Room", "One Room", 1, 12, "Completed", "NOT YET"),
("One Room: Second Season - Hanasaka Yui no Prologue", "One Room 2nd Season: Hanasaka Yui's Prologue", "OVA 1.1", 1, "Completed", "NOT YET"),
("One Room 2", "One Room 2", 2, 12, "Completed", "NOT YET"),
("One Room 3", "One Room 3", 3, 12, "Completed", "NOT YET"),
("Azumanga Daiou", "Azumanga Daiou", 1, 26, "Completed", "NOT YET"),
("Black Lagoon", "Black Lagoon", 1, 12, "Completed", "NOT YET"),
("Black Lagoon: The Second Barrage", "Black Lagoon: The Second Barrage", 2, 12, "Completed", "NOT YET"),
("Psycho-Pass", "Psycho-Pass", 1, 22, "Completed", "NOT YET"),
("Psycho-Pass 2", "Psycho-Pass 2", 2, 11, "Completed", "NOT YET"),
("Psycho-Pass 3", "Psycho-Pass 3", 3, 8, "Completed", "NOT YET"),
("Nijiro Days", "Rainbow Days", 1, 24, "Completed", "NOT YET"),
("Nijiro Days OAD", "Rainbow Days OAD", "OVA", 1, "Completed", "NOT YET"),
("Lovely★Complex", "Lovely Complex", 1, 24, "Completed", "NOT YET"),
("D.Gray-man", "D.Gray-man", 1, 103, "Completed", "NOT YET"),
("D.Gray-man Hallow", "D.Gray-man Hallow", 2, 13, "Completed", "NOT YET"),
("ACCA: 13-ku Kansatsu-ka", "ACCA: 13-Territory Inspection Dept", 1, 12, "Completed", "NOT YET"),
("Yuukoku no Moriarty", "Moriarty the Patriot", 1, 11, "Completed", "NOT YET"),
("Yuukoku no Moriarty Part 2", "Moriarty the Patriot Part 2", 2, 13, "Completed", "NOT YET"),
("Shakugan no Shana", "Shakugan no Shana", 1, 24, "Completed", "NOT YET"),
("Shakugan no Shana II", "Shakugan no Shana II", 2, 24, "Completed", "NOT YET"),
("Shakugan no Shana III", "Shakugan no Shana III", 3, 24, "Completed", "NOT YET"),
("Queen's Blade: Rurou no Senshi", "Queen's Blade: The Exiled Virgin", 1, 12, "Completed", "NOT YET"),
("Queen's Blade: Gyokuza wo Tsugu Mono", "Queen's Blade: Inheritor of the Throne", 2, 12, "Completed", "NOT YET"),
("Queen's Blade: Rebellion", "Queen's Blade Rebellion", 3, 12, "Completed", "NOT YET"),
("Battle Vixens: Ikki Tousen", "Battle Vixens: Ikki Tousen", 1, 13, "Completed", "NOT YET"),
("Dragon Destin: Ikki Tousen", "Dragon Destin: Ikki Tousen", 2, 12, "Completed", "NOT YET"),
("Great Guardians: Ikki Tousen", "Great Guardians: Ikki Tousen", 3, 12, "Completed", "NOT YET"),
("Xtreme Xecutor: Ikki Tousen", "Xtreme Xecutor: Ikki Tousen", 4, 12, "Completed", "NOT YET"),
("Shin: Ikki Tousen", "Shin: Ikki Tousen", 5, 3, "Completed", "NOT YET"),
("Galaxy Angel", "Galaxy Angel", 1, 24, "Completed", "NOT YET"),
("Galaxy Angel Z", "Galaxy Angel Z", 2, 9, "Completed", "NOT YET"),
("Galaxy Angel A", "Galaxy Angel A", 3, 26, "Completed", "NOT YET"),
("Galaxy Angel X", "Galaxy Angel X", 4, 13, "Completed", "NOT YET"),
("Love Get Chu: Miracle Seiyou Hakusho", "Love Get Chu: Miracle Seiyou Hakusho", 1, 25, "Completed", "NOT YET"),
("Yuuki Yuuna wa Yuusha de Aru", "Yuki Yuna is a Hero", 1, 12, "Completed", "NOT YET"),
("Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou", "Yuki Yuna is a Hero: The Washio Sumi Chapter", 2, 6, "Completed", "NOT YET"),
("Yuuki Yuuna wa Yuusha de Aru: Hidamari", "Yuki Yuna is a Hero: A Sunny Place", "OVA 2.1", 1, "Completed", "NOT YET"),
("Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou", "Yuki Yuna is a Hero: The Hero Chapter", 3, 6, "Completed", "NOT YET"),
("Yuuki Yuuna wa Yuusha de Aru: Dai-Mankai no Shou", "Yuki Yuna is a Hero: The Great Mankai Chapter", 4, 12, "Completed", "NOT YET"),
("Shinrei Tantei Yakumo", "Psychic Detective Yakumo", 1, 13, "Completed", "NOT YET"),
("Ganbare, Douki-chan", "Ganbare, Douki-chan", 1, 12, "Completed", "NOT YET"),
("Key the Metal Idol", "Key the Metal Idol", 1, 15, "Completed", "NOT YET"),
("Maou-sama no Machizukuri!: Saikyou no Dungeon wa Kindai Toshi", "The Devil is Making City", 1, "?", "?", "NOT YET"),
("Alice to Zouroku", "Alice & Zoroku", 1, 12, "Completed", "NOT YET"),
("Alice to Teresu no Maboroshi Koujou", "Maboroshi", "MOVIE", 1, "Completed", "NOT YET"),
("Soushin Shoujo Matoi", "Matoi the Sacred Slayer", 1, 12, "Completed", "NOT YET"),
("Kara no Kyoukai: Fukan Fuukei", "The Garden of sinners Chapter 1: Thanatos. (Overlooking View)", "MOVIE 1", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Satsujin Kousatsu (Zen)", "The Garden of sinners Chapter 2: …and nothing heart. (Murder Speculation Part A)", "MOVIE 2", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Tsuukaku Zanryuu", "The Garden of sinners Chapter 3: ever cry, never life. (Remaining Sense of Pain)", "MOVIE 3", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Garan no Dou", "The Garden of sinners Chapter 4: garan-no-dou. (The Hollow Shrine)", "MOVIE 4", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Mujun Rasen", "The Garden of sinners Chapter 5: Paradox Paradigm", "MOVIE 5", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Boukyaku Rokuon", "The Garden of sinners Chapter 6: Fairy Tale. (Oblivion Recording)", "MOVIE 6", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Satsujin Kousatsu (Kou)", "The Garden of sinners Chapter 7: ……not nothing heart. (Murder Speculation Part B)", "MOVIE 7", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Shuushou", "The Garden of sinners Chapter 8: The Final Chapter", "MOVIE 8", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Mirai Fukuin", "The Garden of sinners -recalled out summer-", "MOVIE 9", 1, "Completed", "NOT YET"),
("Kara no Kyoukai: Mirai Fukuin - extra chorus", "The Garden of sinners: recalled out summer –extra chorus–", "OVA 9.1", 1, "Completed", "NOT YET"),
("Kotonoha no Niwa", "The Garden of Words", "MOVIE", 1, "Completed", "NOT YET"),
("Ikebukuro West Gate Park", "Ikebukuro West Gate Park", 1, 12, "Completed", "NOT YET"),
("009-1", "009-1", 1, 12, "Completed", "NOT YET"),
("009-1 Special", "009-1 Special", "OVA 1.1", 1, "Completed", "NOT YET"),
("009 Re:Cyborg", "009 Re:Cyborg", "MOVIE", 1, "Completed", "NOT YET"),
("Yi Ren Zhi Xia", "Hitori no Shita - The Outcast", 1, 12, "Completed", "NOT YET"),
("Yi Ren Zhi Xia 2", "Hitori no Shita - The Outcast 2", 2, 24, "Completed", "NOT YET"),
("Yi Ren Zhi Xia 3", "Hitori no Shita 3", 3, 8, "Completed", "NOT YET"),
("Yi Ren Zhi Xia 4", "Hitori no Shita 4", 4, 12, "Completed", "NOT YET"),
("Shinobi no Ittoki", "Shinobi no Ittoki", 1, 12, "Completed", "NOT YET"),
("Aldnoah.Zero", "Aldnoah.Zero", 1, 12, "Completed", "NOT YET"),
("Aldnoah.Zero 2", "Aldnoah.Zero 2", 2, 12, "Completed", "NOT YET"),
("New Game!", "New Game!", 1, 12, "Completed", "NOT YET"),
("New Game!!", "New Game!!", 2, 12, "Completed", "NOT YET"),
("Himouto! Umaru-chan", "Himouto! Umaru-chan", 1, 12, "Completed", "NOT YET"),
("Himouto! Umaru-chan R", "Himouto! Umaru-chan R", 2, 12, "Completed", "NOT YET"),
("Mahoutsukai no Yome", "The Ancient Magus' Bride", 1, 24, "Completed", "NOT YET"),
("Mahoutsukai no Yome 2", "The Ancient Magus' Bride 2", 2, 12, "Completed", "NOT YET"),
("Bubble", "Bubble", "MOVIE", 1, "Completed", "NOT YET"),
("Bokura no Nanokakan Sensou", "Our Seven Day War", "MOVIE", 1, "?", "NOT YET"),
("D4DJ First Mix", "D4DJ First Mix", 1, 13, "Completed", "NOT YET"),
("D4DJ All Mix", "D4DJ All Mix", 2, 12, "Completed", "NOT YET"),
("Denki-Gai no Honya-san", "Denki-Gai no Honya-san", 1, 12, "Completed", "NOT YET"),
("Vlad Love", "Vlad Love", 1, 12, "Completed", "NOT YET"),
("Ranpo Kitan: Game of Laplace", "Rampo Kitan: Game of Laplace", 1, 11, "Completed", "NOT YET"),
("Peach Boy Riverside", "Peach Boy Riverside", 1, 12, "Completed", "NOT YET"),
("Sabikui Bisco", "Rust Eater Bisco", 1, 12, "Completed", "NOT YET"),
("Hai to Gensou no Grimgar", "Grimgar of Fantasy and Ash", 1, 12, "Completed", "NOT YET"),
("Kanamemo", "Kanamemo", 1, 13, "Completed", "NOT YET"),
("Hortensia Saga", "Hortensia Saga", 1, 12, "Completed", "NOT YET"),
("Junketsu no Maria", "Maria the Virgin Witch", 1, 12, "Completed", "NOT YET"),
("Shachou, Battle no Jikan desu!", "Shachibato! President, It's Time for Battle!", 1, 12, "Completed", "NOT YET"),
("Slow Loop", "Slow Loop", 1, 12, "Completed", "NOT YET"),
("Inu ni Nattara Suki na Hito ni Hirowareta", "My Life as Inukai-san’s Dog", 1, 12, "Completed", "NOT YET"),
("I My Me! Strawberry Eggs", "I My Me! Strawberry Eggs", 1, 13, "Completed", "NOT YET"),
("Deaimon: Recipe for Happiness", "Deaimon: Recipe for Happiness", 1, 12, "Completed", "NOT YET"),
("Vampire Knight", "Vampire Knight", 1, 13, "Completed", "NOT YET"),
("Vampire Knight Guilty", "Vampire Knight Guilty", 2, 13, "Completed", "NOT YET"),
("Diabolik Lovers", "Diabolik Lovers", 1, 12, "Completed", "NOT YET"),
("Diabolik Lovers Ⅱ : More,blood", "Diabolik Lovers Ⅱ : More,blood", 2, 12, "Completed", "NOT YET"),
("The Daily Life of a Middle-Aged Online Shopper in Another World", "nan", "nan", "nan", "nan", "nan"),
("Yuru Camp△", "Laid-Back Camp", 1, 12, "Completed", "NOT YET"),
("Yuru Camp△ 2", "Laid-Back Camp 2", 2, 13, "Completed", "NOT YET"),
("Strike Witches", "Strike Witches", 1, 12, "Completed", "NOT YET"),
("Strike Witches 2", "Strike Witches 2", 2, 12, "Completed", "NOT YET"),
("Strike Witches: The Movie", "Strike Witches: The Movie", 3, 1, "Completed", "NOT YET"),
("Strike Witches Operation Victory Arrow", "Strike Witches Operation Victory Arrow", 4, 3, "Completed", "NOT YET"),
("Brave Witches", "Brave Witches", 5, 12, "Completed", "NOT YET"),
("Soredemo Ayumu wa Yosetekuru", "When Will Ayumu Make His Move?", 1, 12, "Completed", "NOT YET"),
("Kuroshitsuji", "Black Butler", 1, 24, "Completed", "NOT YET"),
("Kuroshitsuji: Book of Circus", "Black Butler: Book of Circus", 2, 10, "Completed", "NOT YET"),
("Sakasama no Patema", "Patema Inverted", "MOVIE", 1, "Completed", "NOT YET"),
("Kino no Tabi: the Beautiful World", "Kino's Journey", 1, 13, "Completed", "NOT YET"),
("Sounan desu ka?", "Are You Lost?", 1, 12, "Completed", "NOT YET"),
("AIKa", "AIKa", 1, 27, "Completed", "NOT YET"),
("AIKa R-16: Virgin Mission", "AIKa R-16: Virgin Mission", 2, 3, "Completed", "NOT YET"),
("Aika Zero", "Aika Zero", 3, 3, "Completed", "NOT YET"),
("Kyuuketsuki Sugu Shinu", "The Vampire Dies in No Time", 1, 12, "Completed", "NOT YET"),
("Kyuuketsuki Sugu Shinu 2", "The Vampire Dies in No Time 2", 2, 12, "Completed", "NOT YET"),
("Uma Musume: Pretty Derby", "Uma Musume: Pretty Derby", 1, 13, "Completed", "NOT YET"),
("Uma Musume: Pretty Derby 2", "Uma Musume: Pretty Derby 2", 2, 13, "Completed", "NOT YET"),
("Leadale no Daichi nite", "In the Land of Leadale", 1, 12, "Completed", "NOT YET"),
("Otome wa Boku ni Koishiteru", "Maidens are Falling for Me", 1, 12, "Completed", "NOT YET"),
("Otome wa Boku ni Koishiteru: Futari no Elder", "Maidens are Falling for Me 2", 2, 3, "Completed", "NOT YET"),
("Otome wa Boku ni Koishiteru: Mittsu no Kiraboshi - The Animation", "Maidens are Falling for Me OVA", "OVA 2.1", 1, "Completed", "NOT YET"),
("Zetsuen no Tempest", "Blast of Tempest", 1, 24, "Completed", "NOT YET"),
("Babylon", "Babylon", 1, 12, "Completed", "NOT YET"),
("Servamp", "Servamp", 1, 12, "Completed", "NOT YET"),
("Joshi Kausei", "Joshi Kausei", 1, 12, "Completed", "NOT YET"),
("Magia Record: Mahou Shoujo Madoka☆Magica Gaiden", "Magia Record: Puella Magi Madoka Magica Side Story", 1, 13, "Completed", "NOT YET"),
("Magia Record: Mahou Shoujo Madoka☆Magica Gaiden 2 - Kakusei Zenya", "Magia Record: Puella Magi Madoka Magica Side Story 2 -The Eve of Awakening-", 2, 8, "Completed", "NOT YET"),
("Magia Record: Mahou Shoujo Madoka☆Magica Gaiden Final - Asaki Yume no Akatsuki", "Magia Record: Puella Magi Madoka Magica Side Story Final -Dawn of a Shallow Dream-", "OVA", 4, "Completed", "NOT YET"),
("Kashimashi: Girl Meets Girl", "Girl Meets Girl", 1, 12, "Completed", "NOT YET"),
("Kashimashi: Girl Meets Girl - Shoujo wa Shoujo ni Koi wo Shita", "Girl Meets Girl OVA", "OVA", 1, "Completed", "NOT YET"),
("Valkyrie Drive: Mermaid", "Valkyrie Drive: Mermaid", 1, 12, "Completed", "NOT YET"),
("Sakura Trick", "Sakura Trick", 1, 12, "Completed", "NOT YET"),
("Mikagura Gakuen Kumikyoku", "Mikagura School Suite", 1, 12, "Completed", "NOT YET"),
("Mai-HiME", "Mai-HiME", 1, 26, "Completed", "NOT YET"),
("Adachi to Shimamura", "Adachi and Shimamura", 1, 12, "Completed", "NOT YET"),
("Majo no Tabitabi 2", "Wandering Witch 2", 2, "?", "?", "NOT YET"),
("Youjo Senki 2", "Saga of Tanya the Evil 2", 2, "?", "?", "NOT YET"),
("Senyoku no Sigrdrifa", "Warlords of Sigrdrifa", 1, 12, "Completed", "NOT YET"),
("Tokyo Mew Mew", "Tokyo Mew Mew", 1, 52, "Completed", "NOT YET"),
("Tokyo Mew Mew New~♡", "Tokyo Mew Mew New~♡", 2, 12, "Completed", "NOT YET"),
("Tokyo Mew Mew New~♡ 2", "Tokyo Mew Mew New~♡ 2", 3, 12, "Completed", "NOT YET"),
("Shicao Lao Long Bei Guanyi E Long Zhi Ming", "A Herbivorous Dragon of 5,000 Years Gets Unfairly Villainized", 1, 12, "Completed", "NOT YET"),
("Keppeki Danshi! Aoyama-kun", "Clean Freak! Aoyama kun", 1, 12, "Completed", "NOT YET"),
("Sugar Apple Fairy Tale", "Sugar Apple Fairy Tale", 1, 12, "Completed", "NOT YET"),
("Sugar Apple Fairy Tale 2", "Sugar Apple Fairy Tale 2", 2, 12, "Completed", "NOT YET"),
("Aa! Megami-sama!", "Oh! My Goddess", 1, 24, "Completed", "NOT YET"),
("Aa! Megami-sama!: Sorezore no Tsubasa!", "Oh! My Goddess: Flights of Fancy", 2, 22, "Completed", "NOT YET"),
("Saiki Kusuo no Ψ-nan", "The Disastrous Life of Saiki K", 1, 120, "Completed", "NOT YET"),
("Saiki Kusuo no Ψ-nan 2", "The Disastrous Life of Saiki K 2", 2, 24, "Completed", "NOT YET"),
("Kono Sekai no Tanoshimikata", "Kono Sekai no Tanoshimikata", "MOVIE 1.1", 1, "Completed", "NOT YET"),
("Katsute Kami Datta Kemono-tachi e", "To the Abandoned Sacred Beasts", 1, 12, "Completed", "NOT YET"),
("Shinigami Bocchan to Kuro Maid 2", "The Duke of Death and His Maid 2", 2, 12, "Completed", "NOT YET"),
("Shinigami Bocchan to Kuro Maid 3", "The Duke of Death and His Maid 3", 3, "?", "Airing", "NOT YET"),
("Henjin no Salad Bowl", "A Salad Bowl of Eccentrics", 1, "?", "Airing", "NOT YET"),
("Do It Yourself!!", "Do It Yourself!!", 1, 12, "Completed", "NOT YET"),
("Mushikaburi-hime", "Bibliophile Princess", 1, 12, "Completed", "NOT YET"),
("4-nin wa Sorezore Uso wo Tsuku", "The Little Lies We All Tell", 1, 11, "Completed", "NOT YET"),
("Reiwa no Di Gi Charat", "Reiwa no Di Gi Charat", 1, 16, "Completed", "NOT YET"),
("Cardcaptor Sakura", "Cardcaptor Sakura", 1, 70, "Completed", "NOT YET"),
("Cardcaptor Sakura: Clear Card-hen", "Cardcaptor Sakura: Clear Card", 1, 22, "Completed", "NOT YET"),
("Jijou wo Shiranai Tenkousei ga Guigui Kuru", "My Clueless First Friend", 1, 13, "Completed", "NOT YET"),
("Watashi no Yuri wa Oshigoto desu!", "Yuri Is My Job!", 1, 12, "Completed", "NOT YET"),
("Cross Ange: Tenshi to Ryuu no Rondo", "Cross Ange: Rondo of Angel and Dragon", 1, 25, "Completed", "NOT YET"),
("Gekidol", "Gekidol", 1, 12, "Completed", "NOT YET"),
("Bartender", "Bartender", 1, 11, "Completed", "NOT YET"),
("Rail Wars!", "Rail Wars!", 1, 12, "Completed", "NOT YET"),
("Kandagawa Jet Girls", "Kandagawa Jet Girls", 1, 12, "Completed", "NOT YET"),
("Rewrite", "Rewrite", 1, 13, "Completed", "NOT YET"),
("Rewrite: Moon and Terra", "Rewrite: Moon and Terra", 2, 11, "Completed", "NOT YET"),
("Room Mate", "Room Mate", 1, 12, "Completed", "NOT YET"),
("Hitsugi no Chaika", "Chaika -The Coffin Princess-", 1, 12, "Completed", "NOT YET"),
("Hitsugi no Chaika: AVENGING BATTLE", "Chaika -The Coffin Princess- AVENGING BATTLE", 2, 10, "Completed", "NOT YET"),
("Aishang Ta De Liyou", "The Girl Downstairs", 1, 22, "Completed", "NOT YET"),
("Penguin Musume♥Heart", "Penguin Girl", 1, 22, "Completed", "NOT YET"),
("Saihate no Paladin 2", "The Faraway Paladin 2", 2, "?", "?", "NOT YET"),
("Mahou Shoujo Tokushusen Asuka", "Magical Girl Spec-Ops Asuka", 1, 12, "Completed", "NOT YET"),
("Shokugyou de Sekai Saikyou 3", "From Commonplace to World's Strongest 3", 3, "?", "?", "NOT YET"),
("Tensei Shitara Ken Deshita 2", "Reincarnated as a Sword: I Became a Sword by Transmigrating 2", 2, "?", "?", "NOT YET"),
("Slime Taoshite 300-nen, Shiranai Uchi ni Level MAX ni Nattemashita 2", "I've Been Killing Slimes for 300 Years and Maxed Out My Level 2", 2, "?", "?", "NOT YET"),
("Seirei Gensouki 2", "Spirit Chronicles 2", 2, "?", "?", "NOT YET"),
("Otomege Sekai wa Mob ni Kibishii Sekai desu 2", "Trapped in a Dating Sim: The World of Otome Games Is Tough for Mobs 2", 2, "?", "?", "NOT YET"),
("Danna ga Nani wo Itteiru ka Wakaranai Ken", "I Can't Understand What My Husband Is Saying", 1, 13, "Completed", "NOT YET"),
("Danna ga Nani wo Itteiru ka Wakaranai Ken 2-sure-me", "I Can't Understand What My Husband is Saying 2nd Thread", 2, 13, "Completed", "NOT YET"),
("Ron Kamonohashi", "Deranged Detective", 1, "?", "?", "NOT YET"),
("Mekakucity Actors", "Mekakucity Actors", 1, 12, "Completed", "NOT YET"),
("Diabolik Lovers", "Diabolik Lovers", 1, 12, "Completed", "NOT YET"),
("Diabolik Lovers Ⅱ : More,blood", "Diabolik Lovers Ⅱ : More,blood", 2, 12, "Completed", "NOT YET"),
("Dance with Devils", "Dance with Devils", 1, 12, "Completed", "NOT YET"),
("Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta… (MOVIE)", "My Next Life as a Villainess: All Routes Lead to Doom! MOVIE", "MOVIE 2.1", 1, "?", "NOT YET"),
("Cool Doji Danshi", "Play It Cool, Guys", 1, 24, "Completed", "NOT YET"),
("Ore Monogatari!!", "My Love Story!!", 1, 24, "Completed", "NOT YET"),
("Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei - The Animation", "Danganronpa: The Animation", 1, 13, "Completed", "NOT YET"),
("Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen", "Danganronpa 3: The End of Hope’s Peak High School - Future Arc", 2, 12, "Completed", "NOT YET"),
("Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen", "Danganronpa 3: The End of Hope’s Peak High School - Despair Arc", 3, 11, "Completed", "NOT YET"),
("Super Danganronpa 2.5 Komaeda Nagito to Sekai no Hakaimono", "Super Danganronpa 2.5: Nagito Komaeda and the Destroyer of the World", "OVA 3.1", 1, "Completed", "NOT YET"),
("Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen", "Danganronpa 3: The End of Hope's Peak High School - Hope Arc", "OVA 3.2", 1, "Completed", "NOT YET"),
("Air Gear", "Air Gear", 1, 25, "Completed", "NOT YET"),
("Taboo Tattoo", "Taboo Tattoo", 1, 12, "Completed", "NOT YET"),
("Touken Ranbu: Hanamaru", "Touken Ranbu - Hanamaru", 1, 12, "Completed", "NOT YET"),
("Touken Ranbu: Hanamaru 2", "Touken Ranbu - Hanamaru 2", 2, 12, "Completed", "NOT YET"),
("Kaze no Stigma", "Kaze no Stigma", 1, 24, "Completed", "NOT YET"),
("Momokuri", "Momokuri", 1, 26, "Completed", "NOT YET"),
("Yesterday wo Utatte", "Sing 'Yesterday' for Me", 1, 12, "Completed", "NOT YET"),
("Tales of Zestiria the Cross", "Tales of Zestiria the X", 1, 12, "Completed", "NOT YET"),
("Tales of Zestiria the Cross 2", "Tales of Zestiria the X Season 2", 2, 13, "Completed", "NOT YET"),
("Summer Ghost", "Summer Ghost", "MOVIE", 1, "Completed", "NOT YET"),
("Kumo no Mukou, Yakusoku no Basho", "The Place Promised in Our Early Days", "MOVIE", 1, "Completed", "NOT YET"),
("91 Days", "91 Days", 1, 12, "Completed", "NOT YET"),
("91 Days: Day 13", "91 Days: Shoal of Time", "OVA 1.1", 1, "Completed", "NOT YET"),
("One Punch Man 3", "One Punch Man 3", 3, "?", "?", "NOT YET"),
("Gangsta", "Gangsta", 1, 13, "Completed", "NOT YET"),
("Gate: Jieitai Kanochi nite, Kaku Tatakaeri", "Gate", 1, 12, "Completed", "NOT YET"),
("Gate: Jieitai Kanochi nite, Kaku Tatakaeri 2", "Gate 2", 2, 12, "Completed", "NOT YET"),
("Summer Ghost", "Summer Ghost", "MOVIE", 1, "Completed", "NOT YET"),
("Koutetsujou no Kabaneri", "Kabaneri of the Iron Fortress", 1, 12, "Completed", "NOT YET"),
("Koutetsujou no Kabaneri Soushuuhen Zenpen: Tsudou Hikari", "Kabaneri of the Iron Fortress: Light That Gathers", "MOVIE 1.1", 1, "Completed", "NOT YET"),
("Koutetsujou no Kabaneri Soushuuhen Kouhen: Moeru Inochi", "Kabaneri of the Iron Fortress: Life That Burns", "MOVIE 1.2", 1, "Completed", "NOT YET"),
("Koutetsujou no Kabaneri: Unato Kessen", "Kabaneri of the Iron Fortress: The Battle of Unato", "MOVIE 1.3", 1, "Completed", "NOT YET"),
("Hoshikuzu Telepath", "Stardust Telepath", 1, 12, "Completed", "NOT YET"),
("Hakuouki", "Demon of the Fleeting Blossom", 1, 12, "Completed", "NOT YET"),
("Hakuouki Special", "Hekketsuroku - Kyoto Kaisouroku", 1.1, 1, "Completed", "NOT YET"),
("Hakuouki Hekketsuroku", "Record of the Jade Blood", 2, 10, "Completed", "NOT YET"),
("Hakuouki: Reimeiroku", "Dawn of the Shinsengumi", 3, 12, "Completed", "NOT YET"),
("Kimi no Todoke 3", "From Me to You 3", 3, "?", "?", "NOT YET"),
("Watashi no Shiawase na Kekkon", "My Happy Marriage", 1, 12, "Completed", "NOT YET"),
("Shaman King", "Shaman King", 1, 64, "Completed", "NOT YET"),
("InuYasha", "InuYasha", 1, 167, "Completed", "NOT YET"),
("Inuyasha: Kanketsu-hen", "InuYasha: The Final Act", 2, 26, "Completed", "NOT YET"),
("Hanyou no Yashahime", "Princess Half-Demon", 3, 24, "Completed", "NOT YET"),
("Hanyou no Yashahime: Ni no Shou", "Princess Half-Demon - The Second Act", 4, 24, "Completed", "NOT YET"),
("Isekai ni Kyuuseishu to shite Yobaremashita ga", "The Savior’s Book Cafe in Another World", 1, "?", "?", "NOT YET"),
("Kaze no Tani no Nausicaä", "Nausicaä of the Valley of the Wind", "MOVIE", 1, "Completed", "NOT YET"),
("Tenkuu no Shiro Laputa", "Castle in the Sky", "MOVIE", 1, "Completed", "NOT YET"),
("Tonari no Totoro", "My Neighbor Totoro", "MOVIE", 1, "Completed", "NOT YET"),
("Majo no Takkyuubin", "Kiki's Delivery Service", "MOVIE", 1, "Completed", "NOT YET"),
("Kurenai no Buta", "Porco Rosso", "MOVIE", 1, "Completed", "NOT YET"),
("Mononoke-hime", "Princess Mononoke", "MOVIE", 1, "Completed", "NOT YET"),
("Sen to Chihiro no Kamikakushi", "Spirited Away", "MOVIE", 1, "Completed", "NOT YET"),
("Howl no Ugoku Shiro", "Howl‘s Moving Castle", "MOVIE", 1, "Completed", "NOT YET"),
("Gake no Ue no Ponyo", "Ponyo", "MOVIE", 1, "Completed", "NOT YET"),
("Karigurashi no Arrietty", "The Secret World of Arrietty", "MOVIE", 1, "Completed", "NOT YET"),
("Kaguya-hime no Monogatari", "The Tale of The Princess Kaguya", "MOVIE", 1, "Completed", "NOT YET"),
("Aya to Majo", "Earwig and the Witch", "MOVIE", 1, "Completed", "NOT YET"),
("Drifters", "Drifters", 1, 12, "Completed", "NOT YET"),
("Ballroom e Youkoso", "Welcome to the Ballroom", 1, 24, "Completed", "NOT YET"),
("Goodbye, DonGlees!", "Goodbye, Don Glees!", "MOVIE", 1, "Completed", "NOT YET"),
("Onegai☆Teacher", "Please☆Teacher!", 1, 12, "Completed", "NOT YET"),
("Ojou to Banken-kun", "A Girl & Her Guard Dog", 1, "?", "?", "NOT YET"),
("Vanitas no Carte", "The Case Study of Vanitas", 1, 12, "Completed", "NOT YET"),
("Vanitas no Carte Part 2", "The Case Study of Vanitas Part 2", 2, 12, "Completed", "NOT YET"),
("Rescue Me!", "Rescue Me!", 1, 1, "Completed", "NOT YET"),
("Bokura no Ameiro Protocol", "Protocol: Rain", 1, "?", "?", "NOT YET"),
("Hibike! Euphonium 3", "Sound! Euphonium 3", 3, 13, "Airing", "NOT YET"),
("Yamato Nadeshiko Shichi Henge♥", "The Wallflower", 1, 25, "Completed", "NOT YET"),
("Dead Mount Death Play", "Dead Mount Death Play", 1, 12, "Completed", "NOT YET"),
("Dead Mount Death Play Part 2", "Dead Mount Death Play Part 2", 2, 12, "Airing", "NOT YET"),
("Fuuto Tantei", "Fuuto PI", 1, 12, "Completed", "NOT YET"),
("16bit Sensation: Another Layer", "16bit Sensation: Another Layer", 1, 13, "Completed", "NOT YET"),
("Wo de Tian Jie Nüyou", "My Cultivator Girlfriend", 1, 15, "Completed", "NOT YET"),
("Kagami no Kojou", "Lonely Castle in the Mirror", "MOVIE", 1, "Completed", "NOT YET"),
("Aishang Ta De Liyou", "The Girl Downstairs", 1, 22, "Completed", "NOT YET"),
("Yubisaki to Renren", "A Sign of Affection", 1, 12, "Completed", "NOT YET"),
("Dragon, Ie wo Kau", "Dragon Goes House-Hunting", 1, 12, "Completed", "NOT YET"),
("Flip Flappers", "Flip Flappers", 1, 13, "Completed", "NOT YET"),
("Shiki", "Shiki", 1, 22, "Completed", "NOT YET"),
("Fairy Tail: 100-nen QuestFairy Tail: 100-nen Quest", "Fairy Tail: 100 Years Quest", 1, 12, "Airing", "NOT YET"),
("Sin: Nanatsu no Taizai", "Seven Mortal Sins", 1, 12, "Completed", "NOT YET"),
("Asobi ni Iku yo!", "Cat Planet Cuties", 1, 12, "Completed", "NOT YET"),
("Valkyrie Drive: Mermaid", "Valkyrie Drive: Mermaid", 1, 12, "Completed", "NOT YET"),
("Senyoku no SigrdrifaSenyoku no Sigrdrifa", "Warlords of Sigrdrifa", 1, 12, "Completed", "NOT YET"),
("2.5-jigen no Ririsa", "2.5 Dimensional Seduction", 1, 24, "Airing", "NOT YET"),
("Code Geass: Dakkan no Rozé", "Code Geass: Rozé of the Recapture", 3, 12, "Completed", "NOT YET"),
("Queen's Blade: Rebellion", "Queen's Blade: Rebellion", 1, 12, "Completed", "NOT YET"),
("Solo Leveling Season 2", "Solo Leveling Season 2", 1, 13, "Airing", "NOT YET"),
("Koi wa Futago de Warikirenai", "Love Is Indivisible by Twins", 1, 12, "Completed", "NOT YET"),
("Guild no Uketsukejou desu ga, Zangyou wa Iya nanode Boss wo Solo Toubatsu Shiyou to Omoimasu", "I May Be a Guild Receptionist, but I’ll Solo Any Boss to Clock Out on Time", 1, 12, "Airing", "NOT YET"),
("Fuguushoku 'Kanteishi' ga Jitsu wa Saikyou Datta", "Even Given the Worthless 'Appraiser' Class, I’m Actually the Strongest", 1, 12, "Airing", "NOT YET"),
("My Favorite VTuber Is Scary IRL", "nan", "nan", "nan", "nan", "nan"),
("Okinawa de Suki ni Natta Ko ga Hougen Sugite Tsurasugiru", "Fell in Love with an Okinawan Girl, but I Just Wish I Know What She's Saying", 1, 12, "Airing", "NOT YET"),
("From Old Country Bumpkin to Master Swordsman", "nan", "nan", "nan", "nan", "nan"),
("Kuroiwa Medaka ni Watashi no Kawaii ga Tsuujinai", "Medaka Kuroiwa is Impervious to My Charms", 1, 12, "Airing", "NOT YET"),
("Momentary Lily", "Momentary Lily", 1, 13, "Airing", "NOT YET"),
("Nageki no Bourei wa Intai shitai", "Let This Grieving Soul Retire!", 1, 13, "Completed", "NOT YET"),
("To Your Eternity", "To Your Eternity", 1, 20, "Completed", "NOT YET"),
("Boku no Tsuma wa Kanjou ga Nai", "My Wife Has No Emotion", 1, 12, "Completed", "NOT YET"),
("Elf-san wa Yaserarenai.Elf-san wa Yaserarenai.", "Plus-Sized Elf", 1, 12, "Completed", "NOT YET"),
("Urusai Yatsura", "Urusai Yatsura", "REMAKE 1", 23, "Completed", "NOT YET"),
("Urusai Yatsura Season 3", "Urusai Yatsura Season 3", "REMAKE 2", 23, "Completed", "NOT YET"),
("Gekai Elise", "Doctor Elise: The Royal Lady with the Lamp", 1, 12, "Completed", "NOT YET"),
("Irozuku Sekai no Ashita kara", "IRODUKU: The World in Colors", 1, 13, "Completed", "NOT YET"),
("Kuma Kuma Kuma Bear", "Kuma Kuma Kuma Bear", 1, 12, "Completed", "NOT YET"),
("Kuma Kuma Kuma Bear Punch!", "Kuma Kuma Kuma Bear - Punch!", 2, 12, "Completed", "NOT YET"),
("Kuma Kuma Kuma Bear Punch!", "TOO CUTE CRISIS", 1, 12, "Completed", "NOT YET"),
("Monogatari Series: Off & Monster Season", "Orokamonogatari", 14, 12, "Airing", "NOT YET"),
("Atri -My Dear Moments-", "Atri -My Dear Moments-", 1, 13, "Airing", "NOT YET"),
("Suki demo Kirai na Amanojaku", "My Oni Girl", "MOVIE", 1, "Completed", "NOT YET"),
("Majo to Yajuu", "The Witch and the Beast", 1, 12, "Completed", "NOT YET"),
("Nige Jouzu no Wakagimi", "Nige Jouzu no Wakagimi", 1, 12, "Airing", "NOT YET"),
("Gekkan Mosou Kagaku", "Delusional Monthly Magazine", 1, 12, "Completed", "NOT YET"),
("Paripi Koumei: Road to Summer Sonia", "Ya Boy Kongming!", "MOVIE", 1, "Completed", "NOT YET"),
("Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3", "Classroom of the Elite 3", 3, 13, "Completed", "NOT YET"),
("Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen Season II", "Our Last Crusade or the Rise of a New World Season 2", 2, 12, "Airing", "NOT YET"),
("TasuuketsuTasuuketsu", "Tasuketsu -Fate of the Majority-", 1, 12, "Airing", "NOT YET"),
("Kenka DokugakuKenka Dokugaku", "Viral Hit", 1, 12, "Completed", "NOT YET"),
("Kaijuu 8-gou", "Kaiju No. 8", 1, 12, "Completed", "NOT YET"),
("Vampire Dormitory", "Vampire Dormitory", 1, 12, "Completed", "NOT YET"),
("Kyuujitsu no Warumono-sanKyuujitsu no Warumono-san", "Mr. Villain's Day Off", 1, 12, "Completed", "NOT YET"),
("Yama no Susume: Next SummitYama no Susume: Next Summit", "Encouragement of Climb: Next Summit", 1, 12, "Completed", "NOT YET"),
("Days With My Stepsister", "nan", "nan", "nan", "nan", "nan"),
("NareNare", "nan", "nan", "nan", "nan", "nan"),
("The Elusive Samurai", "nan", "nan", "nan", "nan", "nan"),
("Cider no You ni Kotoba ga Wakiagaru", "Words Bubble Up Like Soda Pop", "MOVIE", 1, "Completed", "NOT YET"),
("Goukon ni Ittara Onna ga Inakatta Hanashi", "How I Attended an All-Guy's Mixer", 1, 12, "Completed", "NOT YET"),
("Saikyou no Shienshoku 'Wajutsushi' de Aru Ore wa Sekai Saikyou Clan wo Shitagaeru", "The Most Notorious 'Talker' Runs the World's Greatest Clan", 1, 12, "Completed", "NOT YET"),
("Raise wa Tanin ga Ii", "Yakuza Fiancé", 1, 12, "Completed", "NOT YET"),
("Sentai Red Isekai de Boukensha ni Naru", "The Red Ranger Become an Adventure in Another World", 1, 12, "Airing", "NOT YET"),
("Mecha Ude", "Mechanical Arms", 1, 12, "Completed", "NOT YET"),
("Sayounara Ryuusei, Konnichiwa Jinsei", "Good Bye, Dragon Life", 1, 12, "Completed", "NOT YET"),
("Haite Kudasai Takamine-san", "nan", "nan", "nan", "nan", "nan"),
("Sakamoto Days", "Sakamoto Days", 1, 11, "Airing", "NOT YET"),
("Goukon ni Ittara Onna ga Inakatta Hanashi", "How I Attended an All-Guy's Mixer", 1, 12, "Completed", "NOT YET"),
("Ranma 1/2", "nan", "nan", "nan", "nan", "nan"),
("Hitoribocchi no Isekai Kouryaku", "Loner Life in Another World", 1, 12, "Completed", "NOT YET"),
("The Daily Life of a Middle-Aged Online Shopper in Another World", "nan", "nan", "nan", "nan", "nan"),
("NegaPosi Angler", "Negative Positive Angler", 1, 12, "Completed", "NOT YET"),
("Yarinaoshi Reijou wa Ryuutei Heika wo Kouryakuchuu", "Do-Over Damsel Conquers the Dragon Emperor", 1, 12, "Completed", "NOT YET"),
("Chi. Chikyuu no Undou ni Tsuite", "Orb: On The Movements of the Earth", 1, 25, "Airing", "NOT YET"),
("Amagami-san Chi no Enmusubi", "Tying the Knot with an Amagami Sister", 1, 24, "Airing", "NOT YET"),
("Kekkon suru tte, Hontou desu ka", "365 Days to the Wedding", 1, 12, "Completed", "NOT YET"),
("Ao No Hako", "Blue Box", 1, 25, "Airing", "NOT YET");