INSERT INTO `list` (`jap_name`, `eng_name`, `season`, `eps`, `stat`, `watched`) VALUES
("Kono Subarashii Sekai ni Shukufuku wo!", "An Explosion on This Wonderful World", 1, 12, "Completed", "YES"),
("High School DxD", "High School DxD", 1, 12, "Completed", "YES"),
("High School DxD New", "High School DxD New", 2, 12, "Completed", "YES"),
("High School DxD Born", "High School DxD Born", 3, 12, "Completed", "YES"),
("High School DxD Hero", "High School DxD Hero", 4, 12, "Completed", "YES"),
("Monster Musume no Iru Nichijou", "Everyday Life with Monster Girls", 1, 12, "Completed", "YES"),
("Monster Musume no Iru Nichijou : Hobo Mainchi OO!", "Everyday Life with Monster Girls", "OVA", 1, "Completed", "YES"),
("Karakai Jouzu no Takagi-san", "Teasing Master Takagi-san", 1, 12, "Completed", "YES"),
("Isekai Maou to Shoukan Shoujo no Dorei Majutsu", "How Not to Summon a Demon Lord", 1, 12, "Completed", "YES"),
("Princess Lover!", "Princess Lover!", 1, 12, "Completed", "YES"),
("Date a Live", "Date a Live", 1, 12, "Completed", "YES"),
("Date a Live II", "Date a Live II", 2, 10, "Completed", "YES"),
("Date a Live: Date to Date", "Date a Live Encore 1", "OVA 2.1", 1, "Completed", "YES"),
("Gekijouban Date a Live", "Date a Live Mayuri Judgement", "MOVIE 2.1", 1, "Completed", "YES"),
("Date a Live III", "Date a Live III", 3, 12, "Completed", "YES"),
("Charlotte", "Charlotte", 1, 13, "Completed", "YES"),
("Noragami", "Noragami", 1, 12, "Completed", "YES"),
("Noragami Aragoto", "Noragami Aragoto", 2, 13, "Completed", "YES"),
("Tokyo Ghoul", "Tokyo Ghoul", 1, 12, "Completed", "YES"),
("Tokyo Ghoul √A", "Tokyo Ghoul √A", 2, 12, "Completed", "YES"),
("Tokyo Kushu:re", "Tokyo Ghoul:re", 3, 12, "Completed", "YES"),
("Tokyo Kushu:re 2", "Tokyo Ghoul:re 2", 4, 12, "Completed", "YES"),
("Akiba's Trip The Animation", "Akiba's Trip The Animation", 1, 13, "Completed", "YES"),
("Absolute Duo", "Absolute Duo", 1, 12, "Completed", "YES"),
("Seireitsukai no Blade Dance", "Bladedance of Elementalers", 1, 12, "Completed", "YES"),
("Seireitsukai no Blade Dance Specials", "Seireitsukai no Blade Dance Specials", "OVA", 1, "Completed", "YES"),
("Blend - S", "Blend - S", 1, 12, "Completed", "YES"),
("Kimi no Nawa", "Your Name", "MOVIE", 1, "Completed", "YES"),
("Kobayashi-san Chi no Maidragon", "Miss Kobayashi's Dragon Maid", 1, 13, "Completed", "YES"),
("Kobayashi-san Chi no Maidragon OVA", "Miss Kobayashi's Dragon Maid", "OVA 1.1", 1, "Completed", "YES"),
("Kobayashi-san Chi no Maidragon S", "Miss Kobayashi's Dragon Maid S", 2, 12, "Completed", "YES"),
("Koe no Katachi", "Silent Voice", "MOVIE", 1, "Completed", "YES"),
("Sword Art Online", "Sword Art Online", 1, 25, "Completed", "YES"),
("Sword Art Online II", "Sword Art Online II", 2, 24, "Completed", "YES"),
("Sword Art Online: Alicization", "Sword Art Online: Alicization", 3, 24, "Completed", "YES"),
("Sword Art Online: Alicization - War of Underworld", "Sword Art Online: Alicization - War of Underworld", 4, 12, "Completed", "YES"),
("Shigatsu wa Kimi no Uso", "Your Lie in April", 1, 22, "Completed", "YES"),
("Sakurasou no Pet Na Kanojo", "The Pet of Sakurasou", 1, 23, "Completed", "YES"),
("Astarotte no Omocha", "Astarotte's Toy", 1, 12, "Completed", "YES"),
("Boku wa Tomodachi ga Sukunai Ep 0", "Boku wa Tomodachi ga Sukunai Ep 0", "OVA", 1, "Completed", "YES"),
("Boku wa Tomodachi ga Sukunai", "Boku wa Tomodachi ga Sukunai", 1, 12, "Completed", "YES"),
("Boku wa Tomodachi ga Sukunai Next", "Boku wa Tomodachi ga Sukunai Next", 2, 12, "Completed", "YES"),
("Campione! Matsurowanu Kamigami to Kamigoroshi no Maou", "Campione! Matsurowanu Kamigami to Kamigoroshi no Maou", 1, 13, "Completed", "YES"),
("Akame ga Kill!", "Akame ga Kill!", 1, 24, "Completed", "YES"),
("Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita", "I Couldn't Become a Hero, So I Reluctantly Decided to Get a Job", 1, 12, "Completed", "YES"),
("Hagure Yuusha no Aesthetica", "Aesthetica of a Rogue Hero", 1, 12, "Completed", "YES"),
("Hajimete no Gal", "My First Girlfriend is a Gal", 1, 10, "Completed", "YES"),
("Hundred", "Hundred", 1, 12, "Completed", "YES"),
("Gakuen Mokushiroku", "High School of the Dead", 1, 12, "Completed", "YES"),
("Re:Zero kara Hajimeru Isekai Seikatsu", "Re:Zero Starting Life in Another World", 1, 25, "Completed", "YES"),
("Re:Zero kara Hajimeru Isekai Seikatsu- Season 2", "Re:Zero Starting Life in Another World- Season 2", 2, 13, "Completed", "YES"),
("Re:Zero kara Hajimeru Isekai Seikatsu- Season 2 Part 2", "Re:Zero Starting Life in Another World- Season 2 Part 2", 3, 12, "Completed", "YES"),
("Ichiban Ushiro no Daimaou", "Demon King Daimaou", 1, 12, "Completed", "YES"),
("Clannad", "Clannad", 1, 23, "Completed", "YES"),
("Ansatsu Kyoushitsu", "Assasination Classroom", 1, 22, "Completed", "YES"),
("Ansatsu Kyoushitsu 2", "Assasination Classroom 2", 2, 25, "Completed", "YES"),
("Assasination Classroom the Movie: 365-nichi no Jikan", "Assasination Classroom the Movie: 365 Days' Time", "MOVIE 2.1", 1, "Completed", "YES"),
("Chuunibyou demo Koi ga Shitai!", "Love, Chunibyo & Other Delusions", 1, 12, "Completed", "YES"),
("Chuunibyou demo Koi ga Shitai! Ren", "Love, Chunibyo & Other Delusions - Heart Throb -", 2, 12, "Completed", "YES"),
("Takanashi Rikka Kai : Chuunibyou demo Koi ga Shitai! Movie", "Love, Chunibyo & Other Delusions: Rikka Version", "MOVIE", 1, "Completed", "YES"),
("Chuunibyou demo Koi ga Shitai! Rikka Wars", "Love, Chunibyo & Other Delusions - Heart Throb -: The Rikka Wars", "OVA 2.1", 1, "Completed", "YES"),
("Chuunibyou demo Koi ga Shitai!: Take on Me", "Love, Chunibyo & Other Delusions; Take on Me", "MOVIE 2.1", 1, "Completed", "YES"),
("Mayo Chiki!", "Mayo Chiki!", 1, 13, "Completed", "YES"),
("Aho Girl", "Aho Girl", 1, 12, "Completed", "YES"),
("Plastic Memories", "Plastic Memories", 1, 13, "Completed", "YES"),
("Gabriel Dropout", "Gabriel Dropout", 1, 12, "Completed", "YES"),
("Koi to Senkyo to Chocolate", "Love, Election and Chocolate", 1, 12, "Completed", "YES"),
("Eromanga-sensei", "Eromanga-sensei", 1, 12, "Completed", "YES"),
("Sora no Otoshimono", "Heaven's Lost Property", 1, 13, "Completed", "YES"),
("Sora no Otoshimono: Forte", "Heaven's Lost Property: Forte", 2, 12, "Completed", "YES"),
("Sora no Otoshimono Final: Eien no Watashi no Torikago", "Heaven’s Lost Property Final – The Movie: Eternally My Master", "MOVIE 2.1", 1, "Completed", "YES"),
("Nisekoi", "Nisekoi", 1, 20, "Completed", "YES"),
("Nisekoi:", "Nisekoi:", 2, 12, "Completed", "YES"),
("Seto no Hanayome", "My Bride is a Mermaid", 1, 26, "Completed", "YES"),
("Tsurezure Children", "Tsuredure Children", 1, 12, "Completed", "YES"),
("Onii-chan Dakedo Ai Sae Areba Kankeinai yo ne!", "As Long as There's Love, It Doesn't Matter If He Is My Brother, Right?", 1, 12, "Completed", "YES"),
("Sumomomo Momomo: Chijou Saikyou no Yome", "Sumomomo Momomo: Chijou Saikyou no Yome", 1, 22, "Completed", "YES"),
("Renai Boukun", "Love Tyrant", 1, 12, "Completed", "YES"),
("Omamori Himari", "Omamori Himari", 1, 12, "Completed", "YES"),
("Daitoshokan no Hitsujikai", "A Good Librarian Like a Good Shepherd", 1, 12, "Completed", "YES"),
("Dakara Boku wa, H ga Dekinai", "So, I Can't Play H!", 1, 12, "Completed", "YES"),
("Gakusen Toshi Asterisk", "The Asterisk War", 1, 12, "Completed", "YES"),
("Gakusen Toshi Asterisk 2", "The Asterisk War 2", 2, 12, "Completed", "YES"),
("Haiyore! Nyaruko-san", "Nyaruko: Crawling with Love!", 1, 12, "Completed", "YES"),
("Haiyore! Nyaruko-san W", "Nyaruko-san: Another Crawling Chaos W", 2, 12, "Completed", "YES"),
("Haiyore! Nyaruko-san F", "Nyaruko-san: Another Crawling Chaos F", "OVA 2.1", 1, "Completed", "YES"),
("Harukana Receive", "Harukana Receive", 1, 12, "Completed", "YES"),
("Hoshizora e Kakaru Hashi", "A Bridge to the Starry Skies", 1, 12, "Completed", "YES"),
("Hoshizora e Kakaru Hashi Special", "A Bridge to the Starry Skies Special", "OVA", 1, "Completed", "YES"),
("Uchiage Hanabi, Shita kara Miru ka? Yoko kara Miru ka?", "Fireworks", "MOVIE", 1, "Completed", "YES"),
("Hyakka Ryouran: Samurai Girls", "Samurai Girls", 1, 12, "Completed", "YES"),
("Hyakka Ryouran : Samurai Bride", "Samurai Bride", 2, 12, "Completed", "YES"),
("Hyakka Ryouran: Samurai After", "Samurai After", "OVA 2.1", 2, "Completed", "YES"),
("IS: Infinite Stratos", "IS: Infinite Stratos", 1, 12, "Completed", "YES"),
("IS: Infinite Stratos 2", "IS: Infinite Stratos 2", 2, 12, "Completed", "YES"),
("IS: Infinite Stratos 2 - Hitonatsu no Omoide", "IS: Infinite Stratos 2 - Hitonatsu no Omoide", "OVA 2.1", 1, "Completed", "YES"),
("IS: Infinite Stratos - World Purge-hen", "IS: Infinite Stratos - World Purge-hen", "OVA 2.2", 1, "Completed", "YES"),
("IS: Infinite Stratos 2 - Infinite Wedding", "IS: Infinite Stratos 2 - Infinite Wedding", "OVA 2.3", 1, "Completed", "YES"),
("Kanokon", "Kanokon: The Girl Who Cried Fox", 1, 12, "Completed", "YES"),
("Kanokon Special", "Kanokon Special", "SPECIALS", 12, "Completed", "YES"),
("Machine-Doll wa Kizutsukanai", "Unbreakable Machine-Doll", 1, 12, "Completed", "YES"),
("Kotoura-san", "The Troubled Life of Miss Kotoura", 1, 12, "Completed", "YES"),
("Angel Beats", "Angel Beats", 1, 12, "Completed", "YES"),
("Madan no Ou to Vanadis", "Lord Marksman and Vanadis", 1, 13, "Completed", "YES"),
("Goblin Slayer", "Goblin Slayer", 1, 12, "Completed", "YES"),
("Mahou Sensei Negima!", "Negima!", 1, 26, "Completed", "YES"),
("Mahou Sensei Negima! Anime Final", "Mahou Sensei Negima! Anime Final", "MOVIE 1.1", 1, "Completed", "YES"),
("Mahou Sensei Negima! Shiroki Tsubasa Ala Alba", "Mahou Sensei Negima! Shiroki Tsubasa Ala Alba", "OVA 1.1", 1, "Completed", "YES"),
("Mahou Sensei Negima! Mou Hitotsu no Sekai", "Mahou Sensei Negima! Mou Hitotsu no Sekai", "OVA 1.2", 4, "Completed", "YES"),
("Maken-ki!", "Maken-Ki! Battling Venus", 1, 12, "Completed", "YES"),
("Maken-ki! 2", "Maken-Ki! Battling Venus 2", 2, 10, "Completed", "YES"),
("Maji de Watashi ni Koi Shinasai!", "Oh! Samurai Girls", 1, 12, "Completed", "YES"),
("Mangaka-san to Assistant-san to", "The Comic Artist & His Assistants", 1, 12, "Completed", "YES"),
("Mangaka-san to Assistant-san to Animation Special", "The Comic Artist & His Assistants Special", "OVA", 1, "Completed", "YES"),
("Masou Gakuen HxH", "Hybrid x Heart Magias Academy Ataraxia", 1, 12, "Completed", "YES"),
("MM!", "MM!", 1, 12, "Completed", "YES"),
("Medaka Box", "Medaka Box", 1, 12, "Completed", "YES"),
("Medaka Box Abnormal", "Medaka Box Abnormal", 2, 12, "Completed", "YES"),
("Military", "Military", 1, 12, "Completed", "YES"),
("Yahari Ore no Seishun Love Comedy wa Machigatteiru", "My Teen Romantic Comedy SNAFU", 1, 12, "Completed", "YES"),
("Yahari Ore no Seishun Love Comedy wa Machigatteiru Zoku", "My Teen Romantic Comedy SNAFU TOO!", 2, 13, "Completed", "YES"),
("Netoge no Yome wa Onnanoko ja Nai to Omotta?", "And you thought there is never a girl online?", 1, 12, "Completed", "YES"),
("Zombieland Saga", "Zombieland Saga", 1, 12, "Completed", "YES"),
("No Game No Life", "No Game, No Life", 1, 12, "Completed", "YES"),
("No Game No Life: Zero", "No Game, No Life: Zero", "MOVIE 1.1", 1, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka", "Is It Wrong to Try to Pick Up Girls in a Dungeon?", 1, 13, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Gaiden: Sword Oratoria", "Sword Oratoria: Is it Wrong to Try to Pick Up Girls in a Dungeon? On the Side", 1.1, 12, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka: Orion no Ya", "Is It Wrong to Try to Pick Up Girls in a Dungeon?: Arrow of the Orion", "MOVIE 1.1", 1, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka II", "Is It Wrong to Try to Pick Up Girls in a Dungeon? II", 2, 12, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III", "Is It Wrong to Try to Pick Up Girls in a Dungeon? III", 3, 12, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka IV", "Is It Wrong to Try to Pick Up Girls in a Dungeon? IV", 4, 11, "Completed", "YES"),
("Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai", "Rascal Does Not Dream of Bunny Girl Senpai", 1, 13, "Completed", "YES"),
("Satsuriku no Tenshi", "Angel of Death", 1, 12, "Completed", "YES"),
("Hotarubi no Mori e", "Into the Forest of Fireflies' Light", "MOVIE", 1, "Completed", "YES"),
("Hyouka", "Hyouka", 1, 22, "Completed", "YES"),
("Trinity Seven", "Trinity Seven", 1, 12, "Completed", "YES"),
("Trinity Seven Movie - Yuukyuu Toshokan to Renkinjutsu Shoujo", "Trinity Seven: Eternal Library & Alchemic Girl", "MOVIE 1.1", 1, "Completed", "YES"),
("Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai", "A Boring World Where the Concept of Dirty Jokes Doesn’t Exist", 1, 12, "Completed", "YES"),
("Busou Shoujo Machiavellianism", "Armed Girl's Machiavellism", 1, 12, "Completed", "YES"),
("Aishen Qiaokeli-ING...", "Cupid's Chocolates", 1, 15, "Completed", "YES"),
("Aishen Qiaokeli-ING...", "Cupid's Chocolates II", 2, 15, "Completed", "YES"),
("Saijaku Muhai no Bahamut", "Undefeated Bahamut Chronicle", 1, 12, "Completed", "YES"),
("Ouran Koukou Host Club", "Ouran High School Host Club", 1, 26, "Completed", "YES"),
("Mahou Sensou", "Magical Warfare", 1, 12, "Completed", "YES"),
("Gokukoku no Brynhildr", "Brynhildr in the Darkness", 1, 13, "Completed", "YES"),
("Photokano", "Photokano", 1, 13, "Completed", "YES"),
("Summer Wars", "Summer Wars", "MOVIE", 1, "Completed", "YES"),
("Kuzu no Honkai", "Scum's Wish", 1, 12, "Completed", "YES"),
("Tamako Love Story", "Tamako Love Story", "MOVIE", 1, "Completed", "YES"),
("Masamune-kun no Revenge", "Masamune-kun's Revenge", 1, 12, "Completed", "YES"),
("Code Breaker", "Code Breaker", 1, 13, "Completed", "YES"),
("Seiken Tsukai no World Break", "World Break: Aria of Curse for a Holy Swordsman", 1, 12, "Completed", "YES"),
("Strike the Blood", "Strike the Blood", 1, 24, "Completed", "YES"),
("Strike the Blood II", "Strike the Blood II", 2, 8, "Completed", "YES"),
("Tokyo Ravens", "Tokyo Ravens", 1, 24, "Completed", "YES"),
("Tonari no Kyuuketsuki-san", "Ms. vampire who lives in my neighborhood", 1, 12, "Completed", "YES"),
("Violetever Garden", "Violetever Garden", 1, 13, "Completed", "YES"),
("Senran Kagura", "Senran Kagura: Ninja Flash!", 1, 12, "Completed", "YES"),
("Senran Kagura Shinovi Master: Tokyo Youma-hen", "Senran Kagura: Shinovi Master", 2, 12, "Completed", "YES"),
("Tonari no Seki-kun", "The Master of Killing Time", 1, 21, "Completed", "YES"),
("Jashin-chan Dropkick", "Dropkick on My Devil", 1, 11, "Completed", "YES"),
("Saenai Heroine no Sodatekata", "How to Raise a Boring Girlfriend", 1, 12, "Completed", "YES"),
("Saenai Heroine no Sodatekata ♭", "How to Raise a Boring Girlfriend ♭", 2, 11, "Completed", "YES"),
("Musaigen no Phantom World", "Myriad Colors Phantom World", 1, 13, "Completed", "YES"),
("Onee-chan ga Kita", "My Big Sister Arrived", 1, 12, "Completed", "YES"),
("Ore ga Ojou-sama Gakkou ni 'Shomin Sample' Toshite Gets-Sareta Ken", "Shomin Sample", 1, 12, "Completed", "YES"),
("Hataraku Saibou", "Cells at Work!", 1, 13, "Completed", "YES"),
("Hyakuren no Haou to Seiyaku no Valkyria", "The Master of Ragnarök & Blesser of Einherjar", 1, 12, "Completed", "YES"),
("Sunoharasou no Kanrinin-san", "Miss Caretaker of Sunohara-sou", 1, 12, "Completed", "YES"),
("Yuragi-sou no Yuuna-san", "Yuuna and the Haunted Hot Springs", 1, 12, "Completed", "YES"),
("Tensei Shitara Slime Datta Ken", "That Time I Got Reincarnated as a Slime", 1, 24, "Completed", "YES"),
("Tensei Shitara Slime Datta Ken II", "That Time I Got Reincarnated as a Slime II", 2, 12, "Completed", "YES"),
("ensei Shitara Slime Datta Ken II Part 2;", "That Time I Got Reincarnated as a Slime II Part 2", 3, 12, "Completed", "YES"),
("Hidan no Aria", "Aria the Scarlet Ammo", 1, 12, "Completed", "YES"),
("Hidan no Aria AA", "Aria the Scarlet Ammo AA", 2, 12, "Completed", "YES"),
("Kono Naka ni Hitori, Imouto ga Iru!", "My Little Sister Is Among Them!", 1, 12, "Completed", "YES"),
("Go-toubun no Hanayome", "The Quintessential Quintuplets", 1, 12, "Completed", "YES"),
("Ore no Kanojo to Osananajimi ga Shuraba Sugiru", "Oreshura", 1, 13, "Completed", "YES"),
("Baka to Test to Shoukanjuu", "Baka and Test - Summon the Beasts", 1, 13, "Completed", "YES"),
("Baka to Test to Shoukanjuu: Matsuri", "Baka and Test - Summon the Beasts: Matsuri", "OVA 1.1", 2, "Completed", "YES"),
("Baka to Test to Shoukanjuu Ni!", "Baka and Test - Summon the Beasts 2", 2, 13, "Completed", "YES"),
("Juuou Mujin no Fafnir", "Unlimited Fafnir", 1, 12, "Completed", "YES"),
("Komori-san wa Kotowarenai!", "Komori-san Can't Decline!", 1, 12, "Completed", "YES"),
("Gekkan Shoujo Nozaki-kun", "Monthly Girls' Nozaki-kun", 1, 12, "Completed", "YES"),
("Taimadou Gakuen 35 Shiken Shoutai", "Anti-Magic Academy: The 35th Test Platoon", 1, 12, "Completed", "YES"),
("Zero no Tsukaima", "The Familiar of Zero", 1, 13, "Completed", "YES"),
("Zero no Tsukaima: Futatsuki no Kishi", "The Familiar of Zero: Knight of the Twin Moons", 2, 12, "Completed", "YES"),
("Zero no Tsukaima: Princesses no Rondo", "The Familiar of Zero: 'Rondo' of Princesses", 3, 12, "Completed", "YES"),
("Zero no Tsukaima F", "The Familiar of Zero F", 4, 12, "Completed", "YES"),
("Youjo Senki", "Saga of Tanya the Evil", 1, 12, "Completed", "YES"),
("Seitokai no Ichizon", "Student Council's Discretion", 1, 12, "Completed", "YES"),
("Seitokai no Ichizon Lvl 2", "Student Council's Discretion Level 2", 2, 10, "Completed", "YES"),
("Akkun to Kanojo", "My Sweet Tyrant", 1, 25, "Completed", "YES"),
("Asobi Asobase", "Asobi Asobase - workshop of fun -", 1, 12, "Completed", "YES"),
("Suki ni Naru Sono Shunkan wo.: Kokuhaku Jikkou Iinkai", "The Moment You Fall in Love", 2, 1, "Completed", "YES"),
("Rokudenashi Majutsu Koushi to Akashic Records", "Akashic Records of Bastard Magic Instructor", 1, 12, "Completed", "YES"),
("Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen", "Kaguya-sama : Love is War", 1, 12, "Completed", "YES"),
("3D Kanojo: Real Girl", "Real Girl", 1, 12, "Completed", "YES"),
("3D Kanojo: Real Girl 2", "Real Girl 2", 2, 12, "Completed", "YES"),
("Wotaku ni Koi wa Muzukashii", "Love is Hard for Otaku", 1, 11, "Completed", "YES"),
("Ryuuou no Oshigoto!", "The Ryuo's Work is Never Done!", 1, 12, "Completed", "YES"),
("Kaichou wa Maid-sama!", "Maid-Sama!", 1, 26, "Completed", "YES"),
("Ueno-san wa Bukiyou", "How clumsy you are, Miss Ueno", 1, 12, "Completed", "YES"),
("Akagami no Shirayuki-hime", "Snow White with the Red Hair", 1, 12, "Completed", "YES"),
("Akagami no Shirayuki-hime 2", "Snow White with the Red Hair 2", 2, 12, "Completed", "YES"),
("Byousoku 5 Centimeter", "5 centimeters per second", "MOVIE", 1, "Completed", "YES"),
("Toki wo Kakeru Shoujo", "The Girl Who Leapt Through Time", "MOVIE", 1, "Completed", "YES"),
("Ao haru ride", "Blue Spring Ride", "MOVIE", 1, "Completed", "YES"),
("Inu x Boku SS", "Inu X Boku Secret Service", 1, 12, "Completed", "YES"),
("Ookami Shoujo to Kuro Ouji", "Wolf Girl and Black Prince", 1, 12, "Completed", "YES"),
("One Punch Man 2", "One Punch Man 2", 2, 12, "Completed", "YES"),
("Midara na Ao-chan wa Benkyou ga Dekinai", "Ao-chan Can't Study!", 1, 12, "Completed", "YES"),
("Uchi no Ko no Tame Naraba, Ore wa Moshikashitara Maou mo Taoseru Kamo Shirenai", "If It's for My Daughter, I'd Even Defeat a Demon Lord", 1, 12, "Completed", "YES"),
("Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?", "Are you willing to fall in love with a pervert, as long as she’s a cutie?", 1, 12, "Completed", "YES"),
("Boku no Kanojo ga Majime Sugiru Shoujo Bitch na Ken", "My Girlfriend is Shobitch", 1, 10, "Completed", "YES"),
("Kimetsu no Yaiba", "Demon Slayer", 1, 26, "Completed", "YES"),
("Kamisama Hajimemashita", "Kamisama Kiss", 1, 13, "Completed", "YES"),
("Tonari no Kaibutsu-kun", "My Little Monster", 1, 13, "Completed", "YES"),
("Osake wa Fuufu ni Natte kara", "Love is Like a Cocktail", 1, 13, "Completed", "YES"),
("Kimi no Suizou wo Tabetai", "I Want to Eat Your Pancreas", "MOVIE", 1, "Completed", "YES"),
("Tejina Senpai", "Magical Sempai", 1, 12, "Completed", "YES"),
("Hentai Ouji to Warawanai Neko", "The 'Hentai' Prince and the Stony Cat", 1, 12, "Completed", "YES"),
("Yosuga no Sora", "In Solitude, Where We Are Least Alone", 1, 12, "Completed", "YES"),
("Keijo!!!!!!!!", "Keijo!!!!!!!!", 1, 12, "Completed", "YES"),
("Qualidea Code", "Qualidea Code", 1, 12, "Completed", "YES"),
("Karakai Jouzu no Takagi-san", "Teasing Master Takagi-san", 2, 12, "Completed", "YES"),
("Strike the Blood III", "Strike the Blood III", 3, 10, "Completed", "YES"),
("Kumamiko", "Girl Meets Bear", 1, 12, "Completed", "YES"),
("Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu", "God's blessing on this wonderful world!- Legend of Crimson", "MOVIE 2.1", 1, "Completed", "YES"),
("Ben-To", "Ben-To", 1, 12, "Completed", "YES"),
("Senryuu Shoujo", "Senryu Girl", 1, 12, "Completed", "YES"),
("Nourin", "No-Rin", 1, 12, "Completed", "YES"),
("Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai", "The Flower We Saw That Day", 1, 11, "Completed", "YES"),
("Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie", "The Flower We Saw That Day. Movie", "MOVIE 1.1", 1, "Completed", "YES"),
("Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai Movie", "Rascal Does Not Dream of a Dreaming Girl", "MOVIE 1.1", 1, "Completed", "YES"),
("Ore no Nounai Sentakushi ga, Gakuen Love Comedy wo Zenryoku de Jama Shiteiru", "My Mental Choices Are Completely Interfering With My School Romantic Comedy", 1, 10, "Completed", "YES"),
("Isuca", "Isuca", 1, 10, "Completed", "YES"),
("Isuca: Gokuraku", "Isuca: Gokuraku", "OVA", 1, "Completed", "YES"),
("Inou-Battle wa Nichijou-kei no Naka de", "When Supernatural Battles Became Commonplace", 1, 12, "Completed", "YES"),
("Nande Koko ni Sensei ga!?", "Why the hell are you here, Teacher!?", 1, 12, "Completed", "YES"),
("Cheating Craft", "Cheating Craft", 1, 12, "Completed", "YES"),
("Kishuku Gakkou no Juliet", "Boarding School Juliet", 1, 12, "Completed", "YES"),
("Sousei no Onmyouji", "Twin Star Exorcists", 1, 50, "Completed", "YES"),
("Ore ga Suki nano wa Imouto dakedo Imouto ja Nai", "My Sister, My Writer", 1, 10, "Completed", "YES"),
("Gamers!", "Gamers!", 1, 12, "Completed", "YES"),
("Rokujouma no Shinryakusha!?", "Invaders of the Rokujoma!?", 1, 12, "Completed", "YES"),
("Nazo no Kanojo X", "Mysterious Girlfriend X", 1, 13, "Completed", "YES"),
("Kono Bijutsubu ni wa Mondai ga Aru!", "This Art Club Has a Problem!", 1, 12, "Completed", "YES"),
("Tada-kun wa Koi wo Shinai", "Tada Never Falls in Love", 1, 13, "Completed", "YES"),
("Shokugeki no Souma: Shin no Sara", "Food Wars! The Fourth Plate", 4, 12, "Completed", "YES"),
("Seitokai Yakuindomo", "Seitokai Yakuindomo", 1, 13, "Completed", "YES"),
("Seitokai Yakuindomo*", "Seitokai Yakuindomo 2", 2, 13, "Completed", "YES"),
("Seitokai Yakuindomo Movie", "Seitokai Yakuindomo the Movie", "MOVIE 2.1", 1, "Completed", "YES"),
("Ryuugajou Nanana no Maizoukin", "Nanana's Buried Treasure", 1, 11, "Completed", "YES"),
("Joukamachi no Dandelion", "Castle Town Dandelion", 1, 12, "Completed", "YES"),
("Yamada-kun to 7-nin no Majo", "Yamada-kun and the Seven Witches", 1, 12, "Completed", "YES"),
("Ore, Twintail ni Narimasu", "Gonna be the Twin-Tail!!", 1, 12, "Completed", "YES"),
("Shinchou Yuusha: Kono Yuusha ga Ore TUEEE Kuse ni Shinchou Sugiru", "Cautious Hero: The Hero Is Overpowered but Overly Cautious", 1, 12, "Completed", "YES"),
("Overlord", "Overlord", 1, 13, "Completed", "YES"),
("Overlord II", "Overlord II", 2, 13, "Completed", "YES"),
("Overlord III", "Overlord III", 3, 13, "Completed", "YES"),
("Sewayaki Kitsune no Senko-san", "The Helpful Fox Senko-san", 1, 12, "Completed", "YES"),
("Nichijou", "My Ordinary Life", 1, 26, "Completed", "YES"),
("Trinity Seven Movie - Tenkuu Toshokan to Shinku no Maou", "Trinity Seven: Heavens Library & Crimson Lord", "MOVIE 1.2", 1, "Completed", "YES"),
("Mirai Nikki", "The Future Diary", 1, 26, "Completed", "YES"),
("Grand Blue", "Grand Blue Dreaming", 1, 12, "Completed", "YES"),
("Hinamatsuri", "Hinamatsuri", 1, 12, "Completed", "YES"),
("Shingeki no Bahamut: Genesis", "Rage of Bahamut: Genesis", 1, 12, "Completed", "YES"),
("Shingeki no Bahamut: Virgin Soul", "Rage of Bahamut: Virgin Soul", 2, 24, "Completed", "YES"),
("Centaur no Nayami", "A Centaur's Life", 1, 12, "Completed", "YES"),
("Gj-bu", "Gj Club", 1, 12, "Completed", "YES"),
("Gj-bu@", "Gj-bu@", "OVA", 1, "Completed", "YES"),
("Denpa Onna to Seishun Otoko", "Ground Control to Psychoelectric Girl", 1, 12, "Completed", "YES"),
("Okusama ga Seitokaichou!", "My Wife is the Student Council President", 1, 12, "Completed", "YES"),
("Okusama ga Seitokaichou+!", "My Wife is the Student Council President+!", 2, 12, "Completed", "YES"),
("Bikini Warriors", "Bikini Warriors", 1, 12, "Completed", "YES"),
("Amaama to Inazuma", "Sweetness & Lightning", 1, 12, "Completed", "YES"),
("ReLife", "ReLife", 1, 13, "Completed", "YES"),
("Mikakunin de Shinkoukei", "Engaged to the Unidentified", 1, 12, "Completed", "YES"),
("Kimi no Todoke", "From Me to You", 1, 25, "Completed", "YES"),
("Kimi no Todoke 2", "From Me to You 2", 2, 12, "Completed", "YES"),
("Owari no Seraph", "Seraph of the End: Vampire Reign", 1, 12, "Completed", "YES"),
("Owari no Seraph: Nagoya Kessen-hen", "Seraph of the End: Battle in Nagoya", 2, 12, "Completed", "YES"),
("Hello World", "Hello World", "MOVIE 2.1", 1, "Completed", "YES"),
("Yuru Yuri", "YuruYuri", 1, 12, "Completed", "YES"),
("Yuru Yuri♪♪", "YuruYuri 2", 2, 12, "Completed", "YES"),
("Yuru Yuri San☆Hai!", "YuruYuri 3", 3, 12, "Completed", "YES"),
("Miru Tights", "Miru Tights", 1, 12, "Completed", "YES"),
("Himegoto", "Himegoto", 1, 13, "Completed", "YES"),
("K-On", "K-On", 1, 13, "Completed", "YES"),
("K-On 2", "K-On 2", 2, 26, "Completed", "YES"),
("K-On Movie", "K-On: The Movie", "MOVIE 2.1", 1, "Completed", "YES"),
("Love Lab", "Love Lab", 1, 13, "Completed", "YES"),
("Shinryaku! Ika Musume", "Squid Girl", 1, 12, "Completed", "YES"),
("Shinryaku! Ika Musume 2", "Squid Girl 2", 2, 12, "Completed", "YES"),
("Shelter", "Shelter", "OVA", 1, "Completed", "YES"),
("Jashin-chan no Dropkick'", "Dropkick on My Devil! Dash", 2, 11, "Completed", "YES"),
("Ookami-san to Shichinin no Nakama-tachi", "Okami-san and Her Seven Companions", 1, 12, "Completed", "YES"),
("Omiai Aite wa Oshiego, Tsuyoki na, Mondaiji", "My Matchmaking Partner Is My Student, An Aggressive Troublemaker", 1, 12, "Completed", "YES"),
("Tsugumomo", "Tsugumomo", 1, 12, "Completed", "YES"),
("Tsugu Tsugumomo", "Tsugumomo 2", 2, 12, "Completed", "YES"),
("Getsuyoubi no Tawawa", "Tawawa on Monday", 1, 12, "Completed", "YES"),
("Koi to Uso", "Love and Lies", 1, 12, "Completed", "YES"),
("Choujigen Game Neptune The Animation", "Hyperdimension Neptunia", 1, 12, "Completed", "YES"),
("JoJo no Kimyou na Bouken", "JoJo's Bizarre Adventure", 1, 26, "Completed", "YES"),
("JoJo no Kimyou na Bouken: Stardust Crusaders", "JoJo's Bizarre Adventure: Stardust Crusaders", 2, 24, "Completed", "YES"),
("JoJo no Kimyou na Bouken: Stardust Crusaders - Battle In Egypt -", "JoJo's Bizarre Adventure: Stardust Crusaders - Battle In Egypt -", 3, 24, "Completed", "YES"),
("JoJo no Kimyou na Bouken: Diamond wa Kudakenai", "JoJo's Bizarre Adventure: Diamond is Unbreakable", 4, 39, "Completed", "YES"),
("JoJo no Kimyou na Bouken: Ougon no Kaze", "JoJo's Bizarre Adventure: Golden Wind", 5, 39, "Completed", "YES"),
("JoJo no Kimyou na Bouken: Stone Ocean", "JoJo's Bizarre Adventure: Stone Ocean", 6, 12, "Completed", "YES"),
("Domestic na Kanojo", "Domestic Girlfriend", 1, 12, "Completed", "YES"),
("Blood Lad", "Blood Lad", 1, 10, "Completed", "YES"),
("Kaguya-sama wa Kokurasetai?: Tensaitachi no Renai Zunousen", "Kaguya-sama : Love is War?", 2, 12, "Completed", "YES"),
("Ore no Imouto ga Konna ni Kawaii Wake ga Nai", "OreImo", 1, 12, "Completed", "YES"),
("Ore no Imouto ga Konna ni Kawaii Wake ga Nai", "OreImo 2", 2, 13, "Completed", "YES"),
("Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu", "I Don't Want to Get Hurt, so I'll Max Out My Defense", 1, 12, "Completed", "YES"),
("Hatena☆Illusion", "Hatena Illusion", 1, 12, "Completed", "YES"),
("Bokutachi wa Benkyou ga Dekinai", "We Never Learn", 1, 13, "Completed", "YES"),
("Bokutachi wa Benkyou ga Dekinai!", "We Never Learn 2", 2, 13, "Completed", "YES"),
("Tate no Yuusha no Nariagari", "The Rising of the Shield Hero", 1, 25, "Completed", "YES"),
("Sayonara Zetsubou Sensei", "Sayonara, Zetsubou-Sensei", 1, 12, "Completed", "YES"),
("Zoku Sayonara Zetsubou Sensei", "Zoku Sayonara Zetsubou Sensei", 2, 13, "Completed", "YES"),
("Zan Sayonara Zetsubou Sensei", "Zan Sayonara Zetsubou Sensei", 3, 13, "Completed", "YES"),
("Ishuzoku Reviewers", "Interspecies Reviewers", 1, 12, "Completed", "YES"),
("Sankarea", "Undying Love", 1, 12, "Completed", "YES"),
("Girls Bravo: First Season", "Girls Bravo", 1, 11, "Completed", "YES"),
("Girls Bravo: Second Season", "Girls Bravo 2", 2, 13, "Completed", "YES"),
("Seikon no Qwaser", "The Qwaser of Stigmata", 1, 24, "Completed", "YES"),
("Seikon no Qwaser II", "The Qwaser of Stigmata II", 2, 12, "Completed", "YES"),
("Rosario to Vampire", "Rosario + Vampire", 1, 13, "Completed", "YES"),
("Rosario to Vampire Capu2", "Rosario + Vampire Capu2", 2, 13, "Completed", "YES"),
("Shokugeki no Souma: Gou no Sara", "Food Wars! The Fifth Plate", 5, 13, "Completed", "YES"),
("Bakemonogatari", "Bakemonogatari", 1, 15, "Completed", "YES"),
("Kizumonogatari Part 1: Tekketsu (Iron Blooded)", "Kizumonogatari Part 1: Tekketsu (Iron Blooded)", "MOVIE 1.1", 1, "Completed", "YES"),
("Kizumonogatari Part 2: Nekketsu (Hot Blooded)", "Kizumonogatari Part 2: Nekketsu (Hot Blooded)", "MOVIE 1.2", 1, "Completed", "YES"),
("Kizumonogatari Part 3: Reiketsu (Cold Blooded)", "Kizumonogatari Part 3: Reiketsu (Cold Blooded)", "MOVIE 1.3", 1, "Completed", "YES"),
("Nisemonogatari", "Nisemonogatari", 5, 11, "Completed", "YES"),
("Nekomonogatari Kuro", "Nekomonogatari Black", 6, 4, "Completed", "YES"),
("Monogatari Series 2", "Monogatari Series 2", 7, 26, "Completed", "YES"),
("Hanamonogatari", "Hanamonogatari", 8, 5, "Completed", "YES"),
("Tsukimonogatari", "Tsukimonogatari", 9, 4, "Completed", "YES"),
("Koyomimonogatari", "Koyomimonogatari", 10, 12, "Completed", "YES"),
("Owarimonogatari", "Owarimonogatari", 11, 12, "Completed", "YES"),
("Owarimonogatari 2", "Owarimonogatari 2", 12, 7, "Completed", "YES"),
("Zoku Owarimonogatari", "Zoku Owarimonogatari", 13, 6, "Completed", "YES"),
("Code Geass: Hangyaku no Lelouch", "Code Geass: Lelouch of the Rebellion", 1, 25, "Completed", "YES"),
("Code Geass: Hangyaku no Lelouch R2", "Code Geass: Lelouch of the Rebellion R2", 2, 25, "Completed", "YES"),
("Code Geass: Fukkatsu no Lelouch", "Code Geass: Lelouch of the Re;surrection", "MOVIE 2.1", 1, "Completed", "YES"),
("Shin Seiki Evangelion", "Neon Genesis Evangelion", 1, 26, "Completed", "YES"),
("Shin Seiki Evangelion Movie: Air / Magokoro wo, Kimi ni", "Neon Genesis Evangelion: The End of Evangelion", "MOVIE 1.1", 1, "Completed", "YES"),
("Shin Seiki Evangelion Movie: Shi to Shinsei", "Neon Genesis Evangelion: Death & Rebirth", "MOVIE 1.2", 1, "Completed", "YES"),
("Evangelion Shin Movie: Jo", "Evangelion: 1.0 You Are (Not) Alone", "MOVIE 2.0", 1, "Completed", "YES"),
("Evangelion Shin Movie: Ha", "Evangelion: 2.0 You Can (Not) Advance", "MOVIE 2.1", 1, "Completed", "YES"),
("Evangelion Shin Movie: Kyuu", "Evangelion: 3.0 You Can (Not) Redo", "MOVIE 2.2", 1, "Completed", "YES"),
("Shin Evangelion Movie:||", "Evangelion: 3.0+1.0 Thrice Upon a Time", "MOVIE 2.3", 1, "Completed", "YES"),
("Mob Psycho 100", "Mob Psycho 100", 1, 12, "Completed", "YES"),
("Mob Psycho 100 II", "Mob Psycho 100 II", 2, 13, "Completed", "YES"),
("Mob Psycho 100 III", "Mob Psycho 100 III", 3, 12, "Completed", "YES"),
("Ore wo Suki nano wa Omae dake ka yo", "Are you the only one who loves me?", 1, 12, "Completed", "YES"),
("Inari, Konkon, Koi Iroha", "Inari Kon Kon", 1, 10, "Completed", "YES"),
("Iya na Kao sare nagara Opantsu Misete Moraitai", "I Want You To Show Me Your Panties With a Disgusted Face", 1, 6, "Completed", "YES"),
("Iya na Kao sare nagara Opantsu Misete Moraitai 2", "I Want You To Show Me Your Panties With a Disgusted Face", 2, 6, "Completed", "YES"),
("Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e", "Classroom of the Elite", 1, 12, "Completed", "YES"),
("Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 2", "Classroom of the Elite 2", 2, 13, "Completed", "YES"),
("Hen Zemi", "Hen Zemi", 1, 13, "Completed", "YES"),
("Majo no Tabitabi", "Wandering Witch: The Journey of Elaina", 1, 12, "Completed", "YES"),
("Bokusatsu Tenshi Dokuro-chan", "Bludgeoning Angel Dokuro-chan", 1, 4, "Completed", "YES"),
("Bokusatsu Tenshi Dokuro-chan 2", "Bludgeoning Angel Dokuro-chan 2", 2, 2, "Completed", "YES"),
("Hinako Note", "Hinako Note", 1, 12, "Completed", "YES"),
("Watashi ga Motete Dousunda", "Kiss Him, Not me", 1, 12, "Completed", "YES"),
("Kaifuku Jutsushi no Yarinaoshi", "Redo of Healer", 1, 12, "Completed", "YES"),
("Yahari Ore no Seishun Love Comedy wa Machigatteiru Kan", "My Teen Romantic Comedy SNAFU Climax!", 3, 12, "Completed", "YES"),
("Val X Love", "Val X Love", 1, 12, "Completed", "YES"),
("Outbreak Company", "Outbreak Company", 1, 12, "Completed", "YES"),
("Isekai wa Smartphone to Tomo ni", "In Another World With My Smartphone", 1, 12, "Completed", "YES"),
("Rakudai Kishi no Cavalry", "Chivalry of a Failed Knight", 1, 12, "Completed", "YES"),
("Kanojo Ga Flag Wo Oraretara", "If Her Flag Breaks", 1, 13, "Completed", "YES"),
("Dokyuu Hentai HxEros", "Super HxEROS", 1, 12, "Completed", "YES"),
("Uzaki-chan wa Asobitai!", "Uzaki-chan Wants to Hang Out!", 1, 12, "Completed", "YES"),
("Amagami SS", "Amagami SS", 1, 25, "Completed", "YES"),
("Amagami SS+ plus", "Amagami SS+ plus", 2, 13, "Completed", "YES"),
("Dr. Stone", "Dr. Stone", 1, 24, "Completed", "YES"),
("Dr. Stone: Stone Wars", "Dr. Stone: Stone Wars", 2, 11, "Completed", "YES"),
("Gochuumon wa Usagi desu ka?", "Is the Order a Rabbit?", 1, 12, "Completed", "YES"),
("Gochuumon wa Usagi desu ka??", "Is the Order a Rabbit? 2", 2, 12, "Completed", "YES"),
("Gochuumon wa Usagi desu ka? BLOOM", "Is the Order a Rabbit? BLOOM", 3, 12, "Completed", "YES"),
("Kanojo, Okarishimasu", "Rent-a-Girlfriend", 1, 12, "Completed", "YES"),
("Kokoro Connect", "Kokoro Connect", 1, 13, "Completed", "YES"),
("Mahouka Koukou no Rettousei", "The Irregular at Magic High School", 1, 26, "Completed", "YES"),
("Sukitte Ii na yo", "Say 'I love you'", 1, 13, "Completed", "YES"),
("Happy Sugar Life", "Happy Sugar Life", 1, 12, "Completed", "YES"),
("Fairy Tail", "Fairy Tail", 1, 328, "Completed", "YES"),
("Kyoukai no Kanata", "Beyond the Boundary", 1, 12, "Completed", "YES"),
("Love Live! School Idol Project", "Love Live! School Idol Project", 1, 13, "Completed", "YES"),
("Love Live! School Idol Project 2", "Love Live! School Idol Project 2", 2, 13, "Completed", "YES"),
("Love Live! The School Idol Movie", "Love Live! The School Idol Movie", "MOVIE 2.1", 1, "Completed", "YES"),
("Love Live! Sunshine!!", "Love Live! Sunshine!!", 3, 13, "Completed", "YES"),
("Love Live! Sunshine!! 2", "Love Live! Sunshine!! 2", 4, 13, "Completed", "YES"),
("Love Live! Sunshine!! The School Idol Movie: Over the Rainbow", "Love Live! Sunshine!! The School Idol Movie: Over the Rainbow", "MOVIE 4.1", 1, "Completed", "YES"),
("Prison School", "Prison School", 1, 12, "Completed", "YES"),
("Bokura wa minna Kawaisou", "The Kawai Complex Guide to Manors and Hostel Behavior", 1, 12, "Completed", "YES"),
("Tonikaku Kawaii", "Over The Moon For You", 1, 12, "Completed", "YES"),
("Jujutsu Kaisen", "Jujutsu Kaisen", 1, 24, "Completed", "YES"),
("Peter Grill to Kenja no Jikan", "Peter Grill and the Philosopher's Time", 1, 12, "Completed", "YES"),
("Gokushufudou", "The Way of the House Husband", 1, 5, "Completed", "YES"),
("Isekai Ittara Honki Dasu", "Jobless Reincarnation", 1, 11, "Completed", "YES"),
("Isekai Ittara Honki Dasu Cour 2", "Jobless Reincarnation Cour 2", 2, 12, "Completed", "YES"),
("Deadman Wonderland", "Deadman Wonderland", 1, 12, "Completed", "YES"),
("Inu to Hasami wa Tsukaiyou", "Dog and Scissors", 1, 12, "Completed", "YES"),
("Dogeza da Tanondemita", "I Tried Asking While Kowtowing.", 1, 12, "Completed", "YES"),
("Horimiya", "Horimiya", 1, 13, "Completed", "YES"),
("Hitoribocchi no Marumaru Seikatsu", "Hitoribocchi no Marumaru Seikatsu", 1, 12, "Completed", "YES"),
("Kakegurui", "Kakegurui", 1, 12, "Completed", "YES"),
("Kakegurui xx", "Kakegurui xx", 2, 12, "Completed", "YES"),
("Kiseijuu: Sei no Kakuritsu", "Parasyte -the maxim-", 1, 24, "Completed", "YES"),
("Punch Line", "Punch Line", 1, 12, "Completed", "YES"),
("Futari Ecchi", "Step Up Love Story", 1, 4, "Completed", "YES"),
("School Days", "School Days", 1, 12, "Completed", "YES"),
("Ookami Kodomo no Ame to Yuki", "Wolf Children", "MOVIE", 1, "Completed", "YES"),
("Another", "Another", 1, 12, "Completed", "YES"),
("Beelzebub-jou no Okinimesu mama", "As Miss Beelzebub Likes it", 1, 12, "Completed", "YES"),
("Death Parade", "Death Parade", 1, 12, "Completed", "YES"),
("Imouto sae Ireba Ii", "A Sister's All You Need", 1, 12, "Completed", "YES"),
("Non Non Biyori", "Non Non Biyori", 1, 12, "Completed", "YES"),
("Non Non Biyori: Okinawa e Ikukoto ni Natta", "Non Non Biyori: We're Going to Okinawa", "OVA 1.1", 1, "Completed", "YES"),
("Non Non Biyori Repeat", "Non Non Biyori Repeat", 2, 12, "Completed", "YES"),
("Non Non Biyori Movie: Vacation", "Non Non Biyori Movie: Vacation", "MOVIE 2.1", 1, "Completed", "YES"),
("Non Non Biyori Nonstop", "Non Non Biyori Nonstop", 3, 12, "Completed", "YES"),
("Isekai Maou to Shoukan Shoujo no Dorei Majutsu Ω", "How Not to Summon a Demon Lord Ω", 2, 10, "Completed", "YES"),
("Sentouin, Hakenshimasu!", "Combatants will be Dispatched", 1, 12, "Completed", "YES"),
("Josee to Tora To Sakana-tachi", "Josee, the Tiger and the Fish", "MOVIE", 1, "Completed", "YES"),
("Elfen Lied", "Elfen Lied", 1, 13, "Completed", "YES"),
("Shuumatsu no Valkyrie", "Records of Ragnarok", 1, 12, "Completed", "YES"),
("Ijiranaide, Nagatoro-san", "Don't Toy With Me, Miss Nagatoro", 1, 12, "Completed", "YES"),
("Ijiranaide, Nagatoro-san 2nd Attack", "Don't Toy With Me, Miss Nagatoro 2nd Attack", 2, 12, "Completed", "YES"),
("Hige wo Soru. Soshite Joshikousei wo Hirou", "After Being Rejected, I Shaved and Took in a High School Runaway", 1, 13, "Completed", "YES"),
("Grisaia no Kajitsu", "The Fruit of Grisaia", 1, 13, "Completed", "YES"),
("Grisaia no Meikyuu", "The Labyrinth of Grisaia", "OVA 1.1", 1, "Completed", "YES"),
("Grisaia no Rakuen", "The Eden of Grisaia", 2, 10, "Completed", "YES"),
("Binbougami ga!", "Good Luck Girl", 1, 13, "Completed", "YES"),
("Maria†Holic", "Maria†Holic", 1, 12, "Completed", "YES"),
("Maria†Holic Alive", "Maria†Holic Alive", 2, 12, "Completed", "YES"),
("Araburu Kisetsu no Otome-domo yo", "O Maidens in Your Savage Season", 1, 12, "Completed", "YES"),
("Jibaku Shounen Hanako-kun", "Toilet Bound Hanako-kun", 1, 12, "Completed", "YES"),
("Plunderer", "Plunderer", 1, 24, "Completed", "YES"),
("Little Busters!", "Little Busters!", 1, 26, "Completed", "YES"),
("Little Busters! Refrain", "Little Busters! Refrain", 2, 13, "Completed", "YES"),
("Tenkuu Shinpan", "High Rise Invasion", 1, 12, "Completed", "YES"),
("Kuusen Madoushi Kouhosei no Kyoukan", "Sky Wizards Academy", 1, 12, "Completed", "YES"),
("Chio-chan no Tsuugakuro", "Chio-chan's School Road", 1, 12, "Completed", "YES"),
("Zombieland Saga Revenge", "Zombieland Saga Revenge", 2, 12, "Completed", "YES"),
("Tanaka-kun wa Itsumo Kedaruge", "Tanaka-kun is Always Listless", 1, 12, "Completed", "YES"),
("Choujin Koukousei-tachi wa Isekai demo Yoyuu de Ikinuku you desu!", "High School Prodigies Have It Easy In Another World", 1, 12, "Completed", "YES"),
("Tachibanakan to Lie Angle", "Love To-LIE-Angle", 1, 12, "Completed", "YES"),
("Little Witch Academia Movie", "Little Witch Academia Movie", "OVA", 1, "Completed", "YES"),
("Little Witch Academia: Mahou-jikake no Parade", "Little Witch Academia: The Enchanted Parade", "MOVIE 1.1", 1, "Completed", "YES"),
("Little Witch Academia", "Little Witch Academia", 1, 25, "Completed", "YES"),
("Brand New Animal", "Brand New Animal", 1, 12, "Completed", "YES"),
("Amagi Brilliant Park", "Amagi Brilliant Park", 1, 13, "Completed", "YES"),
("Gleipnir", "Gleipnir", 1, 13, "Completed", "YES"),
("Princess Connect! Re:Dive", "Princess Connect! Re:Dive", 1, 13, "Completed", "YES"),
("Kami no Tou", "Tower of God", 1, 13, "Completed", "YES"),
("Kannagi", "Crazy Shrine Maidens", 1, 13, "Completed", "YES"),
("Assassins Pride", "Assassins Pride", 1, 12, "Completed", "YES"),
("Kämpfer", "Kämpfer", 1, 12, "Completed", "YES"),
("Demi-chan wa Kataritai", "Interviews with Monster Girls", 1, 12, "Completed", "YES"),
("Shuffle!", "Shuffle!", 1, 24, "Completed", "YES"),
("Shuffle! Memories", "Shuffle! Memories", 2, 12, "Completed", "YES"),
("Kanojo mo Kanojo", "Girlfriend, Girlfriend", 1, 12, "Completed", "YES"),
("Beelzebub", "Beelzebub", 1, 60, "Completed", "YES"),
("Kami nomi zo Shiru Sekai", "The World God Only Knows", 1, 12, "Completed", "YES"),
("Kami nomi zo Shiru Sekai II", "The World God Only Knows II", 2, 12, "Completed", "YES"),
("Kami nomi zo Shiru Sekai: Megami-hen", "The World God Only Knows: Goddesses", 3, 12, "Completed", "YES"),
("Watashi ni Tenshi ga Maiorita!", "An Angel Flew Down to Me", 1, 12, "Completed", "YES"),
("Gakuen Babysitter", "School Babysitters", 1, 13, "Completed", "YES"),
("Enen no Shouboutai", "Fire Force", 1, 24, "Completed", "YES"),
("Enen no Shouboutai 2", "Fire Force 2", 2, 24, "Completed", "YES"),
("Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou", "History’s Strongest Demon King Reincarnates and Goes to School with His Descendants", 1, 13, "Completed", "YES"),
("Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo?", "Problem Children Are Coming From Another World, Aren't They?", 1, 10, "Completed", "YES"),
("Konohana Kitan", "Konohana Kitan", 1, 12, "Completed", "YES"),
("Nerawareta Gakuen", "Psychic School Wars", "MOVIE", 1, "Completed", "YES"),
("Golden Time", "Golden Time", 1, 24, "Completed", "YES"),
("Anne Happy♪", "Anne-Happy", 1, 12, "Completed", "YES"),
("Tsuujou Kougeki ga Zentai Kougeki de Ni-kai Kougeki no Okaasan wa Suki desu ka?", "Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?", 1, 12, "Completed", "YES"),
("Sekirei", "Sekirei", 1, 12, "Completed", "YES"),
("Sekirei: Pure Engagement", "Sekirei: Pure Engagement", 2, 13, "Completed", "YES"),
("Akane Iro ni Somaru Saka", "The Hill Dyed Rose Madder", 1, 12, "Completed", "YES"),
("DearS", "DearS", 1, 12, "Completed", "YES"),
("Boku no Hero Academia 4", "My Hero Academia 4", 4, 25, "Completed", "YES"),
("Boku no Hero Academia 5", "My Hero Academia 5", 5, 25, "Completed", "YES"),
("Boku no Hero Academia 6", "My Hero Academia 6", 5, 25, "Completed", "YES"),
("Akudama Drive", "Akudama Drive", 1, 12, "Completed", "YES"),
("Witch Craft Works", "Witch Craft Works", 1, 12, "Completed", "YES"),
("Denpa Kyoushi", "Ultimate Otaku Teacher", 1, 24, "Completed", "YES"),
("Yumekui Merry", "Dream Eater Merry", 1, 13, "Completed", "YES"),
("Dagashi Kashi", "Dagashi Kashi", 1, 12, "Completed", "YES"),
("Dagashi Kashi 2", "Dagashi Kashi 2", 2, 12, "Completed", "YES"),
("Acchi Kocchi", "Place to Place", 1, 12, "Completed", "YES"),
("Hataraku Maou-sama!", "The Devil is a Part-Timer!", 1, 13, "Completed", "YES"),
("B Gata H Kei", "Yamada's First Time", 1, 12, "Completed", "YES"),
("Tsuki ga Kirei", "Tsuki ga Kirei", 1, 12, "Completed", "YES"),
("Rikei ga Koi ni Ochita no de Shoumei shitemita", "Science Fell in Love, So I Tried to Prove It", 1, 12, "Completed", "YES"),
("C³", "C3", 1, 12, "Completed", "YES"),
("Black Clover", "Black Clover", 1, 170, "Completed", "YES"),
("Black Clover: Mahou Tei no Ken", "Black Clover: Sword of the Wizard King", "MOVIE 1.1", 1, "Completed", "YES"),
("Murenase! Seton Gakuen", "Seton Academy: Join the Pack!", 1, 12, "Completed", "YES"),
("Seiren", "Seiren", 3, 12, "Completed", "YES"),
("Ixion Saga DT", "Ixion Saga DT", 1, 25, "Completed", "YES"),
("D-Frag!", "D-Frag!", 1, 12, "Completed", "YES"),
("Kamisama ni Natta Hi", "The Day I Become a God", 1, 12, "Completed", "YES"),
("Komi-san wa, Komyushou desu", "Komi-san Can't Communicate", 1, 12, "Completed", "YES"),
("Higurashi no Naku Koro ni", "When They Cry Kai", 1, 26, "Completed", "YES"),
("Higurashi no Naku Koro ni Kai", "When They Cry Kai", 2, 24, "Completed", "YES"),
("Higurashi no Naku Koro ni Gou", "When They Cry Gou", 3, 24, "Completed", "YES"),
("Higurashi no Naku Koro ni Sotsu", "When They Cry Sotsu", 4, 15, "Completed", "YES"),
("Moetan", "Moetan", 1, 12, "Completed", "YES"),
("Needless", "Needless", 1, 24, "Completed", "YES"),
("Asu no Yoichi!", "Samurai Harem", 1, 12, "Completed", "YES"),
("Machikado Mazoku", "The Demon Girl Next Door", 1, 12, "Completed", "YES"),
("Danchigai", "Danchigai", 1, 12, "Completed", "YES"),
("Oretachi ni Tsubasa wa Nai: under the innocent sky", "We Without Wings – Under the Innocent Sky", 1, 12, "Completed", "YES"),
("Mashiro no Oto", "Those Snow White Notes", 1, 12, "Completed", "YES"),
("Papa no Iukoto o Kikinasai", "Listen to Me, Girls. I Am Your Father!", 1, 12, "Completed", "YES"),
("Nekopara", "Nekopara", 1, 12, "Completed", "YES"),
("Koisuru Asteroid", "Asteroid in Love", 1, 12, "Completed", "YES"),
("Somali to Mori no Kamisama", "Somali and the Forest Spirit", 1, 12, "Completed", "YES"),
("Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari", "Suppose a Kid from the Last Dungeon Boonies moved to a starter town?", 1, 12, "Completed", "YES"),
("Ichigo Mashimaro", "Strawberry Marshmallow", 1, 12, "Completed", "YES"),
("Shikkakumon no Saikyou Kenja", "The Strongest Sage with the Weakest Crest", 1, 12, "Completed", "YES"),
("Sono Bisque Doll wa Koi wo Suru", "My Dress-Up Darling", 1, 12, "Completed", "YES"),
("Killing Bites", "Killing Bites", 1, 12, "Completed", "YES"),
("Tayutama", "Kiss on my Deity", 1, 12, "Completed", "YES"),
("Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta…", "My Next Life as a Villainess: All Routes Lead to Doom!", 1, 12, "Completed", "YES"),
("Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta… X", "My Next Life as a Villainess: All Routes Lead to Doom! X", 2, 12, "Completed", "YES"),
("Watashi, Nouryoku wa Heikinchi de tte Itta yo ne!", "Didn't I Say to Make My Abilities Average in the Next Life?!", 1, 12, "Completed", "YES"),
("Shokugyou de Sekai Saikyou", "From Commonplace to World's Strongest", 1, 13, "Completed", "YES"),
("Shokugyou de Sekai Saikyou 2", "From Commonplace to World's Strongest 2", 2, 12, "Completed", "YES"),
("Dumbbell Nan Kilo Moteru?", "How Heavy Are the Dumbbells You Lift?", 1, 12, "Completed", "YES"),
("Sora no Aosa wo Shiru Hito yo", "Her Blue Sky", "MOVIE", 1, "Completed", "YES"),
("D.C.: Da Capo", "D.C.~Da Capo~", 1, 26, "Completed", "YES"),
("D.C.S.S.: Da Capo Second Season", "D.C.S.S. ~Da Capo Second Season~", 2, 26, "Completed", "YES"),
("D.C.II", "Da Capo II", 3, 13, "Completed", "YES"),
("D.C.II S.S.", "Da Capo II Second Season", 4, 13, "Completed", "YES"),
("DC.III", "Da Capo III", 5, 13, "Completed", "YES"),
("Subete ga F ni Naru", "The Perfect Insider", 1, 11, "Completed", "YES"),
("Sora Yori mo Tooi Basho", "A Place Further Than the Universe", 1, 13, "Completed", "YES"),
("Nakitai Watashi wa Neko wo Kaburu", "A Whisker Away", "MOVIE", 1, "Completed", "YES"),
("Ni no Kuni", "Ni no Kuni", "MOVIE", 1, "Completed", "YES"),
("Genjitsu Shugi Yuusha no Oukoku Saikenki", "How a Realist Hero Rebuilt the Kingdom", 1, 13, "Completed", "YES"),
("Genjitsu Shugi Yuusha no Oukoku Saikenki 2", "How a Realist Hero Rebuilt the Kingdom 2", 2, 13, "Completed", "YES"),
("Tenshi no 3P!", "Angel's 3Piece!", 1, 12, "Completed", "YES"),
("Maburaho", "Maburaho", 1, 24, "Completed", "YES"),
("Citrus", "Citrus", 1, 12, "Completed", "YES"),
("FragTime", "FragTime", "MOVIE", 1, "Completed", "YES"),
("Yagate Kimi ni Naru", "Bloom into You", 1, 13, "Completed", "YES"),
("Jahy-sama wa Kujikenai!", "The Great Jahy Will Not Be Defeated!", 1, 20, "Completed", "YES"),
("Netsuzou Trap", "Netsuzou Trap", 1, 12, "Completed", "YES"),
("Bungou Stray Dogs", "Bungou Stray Dogs", 1, 12, "Completed", "YES"),
("Bungou Stray Dogs 2", "Bungou Stray Dogs 2", 2, 12, "Completed", "YES"),
("Bungou Stray Dogs: Hitori Ayumu", "Bungou Stray Dogs: Walking Alone", "OVA 2.1", 1, "Completed", "YES"),
("Bungou Stray Dogs: Dead Apple", "Bungou Stray Dogs: Dead Apple", "MOVIE", 1, "Completed", "YES"),
("Bungou Stray Dogs 3", "Bungou Stray Dogs 3", 3, 12, "Completed", "YES"),
("Guilty Crown", "Guilty Crown", 1, 22, "Completed", "YES"),
("Zero Kara Hajimeru Mahou no Sho", "Grimoire of Zero", 1, 12, "Completed", "YES"),
("Mahoutsukai Reimeiki", "The Dawn of the Witch", 2, 12, "Completed", "YES"),
("Hibike! Euphonium", "Sound! Euphonium", 1, 13, "Completed", "YES"),
("Hibike! Euphonium: Kitauji Koukou Suisougaku-bu e Youkoso", "Sound! Euphonium the Movie: Welcome to the Kitauji High School Concert Band", "MOVIE 1", 1, "Completed", "YES"),
("Hibike! Euphonium 2", "Sound! Euphonium 2", 2, 13, "Completed", "YES"),
("Hibike! Euphonium: Todoketai Melody", "Sound! Euphonium The Movie — May the melody reach you!", "MOVIE 2.1", 1, "Completed", "YES"),
("Hibike! Euphonium: Chikai no Finale", "Sound! Euphonium: The Movie - Our Promise: A Brand New Day", "MOVIE 2.2", 1, "Completed", "YES"),
("Ore dake Haireru Kakushi Dungeon", "Hidden Dungeon Only I Can Enter", 1, 12, "Completed", "YES"),
("Hachi-nan tte, Sore wa Nai deshou!", "The 8th Son? Are You Kidding Me?", 1, 12, "Completed", "YES"),
("Joshikousei no Mudazukai", "Wasteful Days of High School Girls", 1, 12, "Completed", "YES"),
("Yuusha, Yamemasu", "I'm Quitting Heroing", 1, 12, "Completed", "YES"),
("Kimi ga Aruji de Shitsuji ga Ore de", "They Are My Noble Masters", 1, 13, "Completed", "YES"),
("Hatsukoi Monster", "First Love Monster", 1, 12, "Completed", "YES"),
("Death March kara Hajimaru Isekai Kyousoukyoku", "Death March to the Parallel World Rhapsody", 1, 12, "Completed", "YES"),
("Kyuukyoku Shinka Shita Full Dive RPG ga Genjitsu yori mo Kusogee Dattara", "Full Dive: This Ultimate Next-Gen Full Dive RPG Is Even Shittier than Real Life!", 1, 12, "Completed", "YES"),
("Suzumiya Haruhi no Shoushitsu", "The Disappearance of Haruhi Suzumiya", "MOVIE", 1, "Completed", "YES"),
("Tantei wa mou, Shindeiru", "The Detective Is Already Dead", 1, 12, "Completed", "YES"),
("Spy x Family", "Spy x Family", 1, 12, "Completed", "YES"),
("Bokutachi no Remake", "Remake Our Life!", 1, 12, "Completed", "YES"),
("Black Bullet", "Black Bullet", 1, 13, "Completed", "YES"),
("Koi to Yobu ni wa Kimochi Warui", "It's Disgusting to Call this Love", 1, 12, "Completed", "YES"),
("Slime Taoshite 300-nen, Shiranai Uchi ni Level MAX ni Nattemashita", "I've Been Killing Slimes for 300 Years and Maxed Out My Level", 1, 12, "Completed", "YES"),
("Manyuu Hiken-chou", "Magic Breast Secret Sword Scroll", 1, 12, "Completed", "YES"),
("Monster Musume no Oisha-san", "Monster Girl Doctor", 1, 12, "Completed", "YES"),
("Dies Irae", "Dies Irae", 1, 11, "Completed", "YES"),
("Runway de Waratte", "Smile Down the Runway", 1, 12, "Completed", "YES"),
("Kiniro Mosaic", "Kiniro Mosaic", 1, 12, "Completed", "YES"),
("Boku dake ga Inai Machi", "Erased", 1, 12, "Completed", "YES"),
("Hataage! Kemono Michi", "Kemono Michi: Rise Up", 1, 12, "Completed", "YES"),
("Chobits", "Chobits", 1, 26, "Completed", "YES"),
("Big Order", "Big Order", 1, 10, "Completed", "YES"),
("Kono Healer, Mendokusai", "Don’t Hurt Me, My Healer!", 1, 12, "Completed", "YES"),
("Kunoichi Tsubaki no Mune no Uchi", "In the Heart of Kunoichi Tsubaki", 1, 13, "Completed", "YES"),
("Ladies Versus Butlers", "Ladies Versus Butlers", 1, 12, "Completed", "YES"),
("Yofukashi no Uta", "Call of the Night", 1, 13, "Completed", "YES"),
("Jujutsu Kaisen 0", "Jujutsu Kaisen 0", "MOVIE", 1, "Completed", "YES"),
("Komi-san wa, Komyushou desu Part 2", "Komi-san Can't Communicate Part 2", 2, 12, "Completed", "YES"),
("Kumo desu ga, Nani ka?", "So I'm a Spider, So What?", 1, 24, "Completed", "YES"),
("Tensai Ouji no Akaji Kokka Saisei Jutsu", "The Genius Prince's Guide to Raising a Nation Out of Debt", 1, 12, "Completed", "YES"),
("Bocchi the Rock", "Bocchi the Rock", 1, 12, "Completed", "YES"),
("Chainsaw Man", "Chainsaw Man", 1, 12, "Completed", "YES"),
("Shuumatsu no Harem", "World's End Harem", 1, 11, "Completed", "YES"),
("Kimetsu no Yaiba: Yuukaku-hen", "Demon Slayer: Entertainment District Arc", 3, 11, "Completed", "YES"),
("Spy x Family Cour 2", "Spy x Family Cour 2", 2, 13, "Completed", "YES"),
("Fuufu Ijou, Koibito Miman", "More than a Married Couple, but Not Lovers", 1, 12, "Completed", "YES"),
("Wonder Egg Priority", "Wonder Egg Priority", 1, 12, "Completed", "YES"),
("Shingeki no Kyojin", "Attack on Titan", 1, 25, "Completed", "YES"),
("Shingeki no Kyojin 2", "Attack on Titan 2", 2, 12, "Completed", "YES"),
("Shingeki no Kyojin 3", "Attack on Titan 3", 3, 12, "Completed", "YES"),
("Shingeki no Kyojin 3 Part 2", "Attack on Titan 3 Part 2", 4, 10, "Completed", "YES"),
("Shingeki no Kyojin: The Final Season", "Attack on Titan: The Final Season", 5, 16, "Completed", "YES"),
("Hunter x Hunter", "Hunter x Hunter", 1, 62, "Completed", "YES"),
("Belle", "Belle", "MOVIE", 1, "Completed", "YES"),
("Toaru Majutsu no Index", "A Certain Magical Index", 1, 24, "Completed", "YES"),
("Toaru Majutsu no Index II", "A Certain Magical Index II", 2, 24, "Completed", "YES"),
("Toaru Majutsu no Index Movie: Endymion no Kiseki", "A Certain Magical Index: The Miracle of Endymion", "MOVIE 2.1", 1, "Completed", "YES"),
("Toaru Majutsu no Index Movie: Endymion no Kiseki - Ga Attari Nakattari", "Toaru Majutsu no Index Movie: Endymion no Kiseki - Ga Attari Nakattari", "OVA 2.2", 1, "Completed", "YES"),
("Toaru Majutsu no Index III", "A Certain Magical Index III", 3, 26, "Completed", "YES"),
("Akikan!", "Akikan!", 1, 12, "Completed", "YES"),
("Renai Flops", "Love Flops", 1, 12, "Completed", "YES"),
("86: Eighty Six", "Eighty Six", 1, 11, "Completed", "YES"),
("86: Eighty Six 2", "Eighty Six 2", 2, 12, "Completed", "YES"),
("takt op.Destiny", "takt op.Destiny", 1, 12, "Completed", "YES"),
("Kawaii dake ja Nai Shikimori-san", "Shikimori's Not Just a Cutie", 1, 12, "Completed", "YES"),
("Jitsu wa Watashi wa", "Actually, I Am", 1, 13, "Completed", "YES"),
("Kono Yo no Hate de Koi wo Utau Shoujo YU-NO", "A Girl Who Chants Love at the Bound of This World", 1, 26, "Completed", "YES"),
("Sasami-san@Ganbaranai", "Sasami-san@Ganbaranai", 1, 12, "Completed", "YES"),
("Bermuda Triangle: Colorful Pastrale", "Bermuda Triangle: Colorful Pastrale", 1, 12, "Completed", "YES"),
("HaNaYaMaTa", "HaNaYaMaTa", 1, 12, "Completed", "YES"),
("Machikado Mazoku 2", "The Demon Girl Next Door 2", 2, 12, "Completed", "YES"),
("Coquelicot-zaka kara", "From Up on Poppy Hill", "MOVIE", 1, "Completed", "YES"),
("Koi wa Sekai Seifuku no Ato de", "Love After World Domination", 1, 12, "Completed", "YES"),
("Lycoris Recoil", "Lycoris Recoil", 1, 13, "Completed", "YES"),
("Tensei Kenja no Isekai Life: Daini no Shokugyo wo Ete, Sekai Saikyou ni Narimashita", "My Isekai Life: I Gained a Second Character Class and Became the Strongest Sage in the World!", 1, 12, "Completed", "YES"),
("Osananajimi ga Zettai ni Makenai Love Come", "Romcom Where The Childhood Friend Won't Lose", 1, 12, "Completed", "YES"),
("Romantic Killer", "Romantic Killer", 1, 12, "Completed", "YES"),
("Akiba Meido Sensou", "Akiba Maid War", 1, 12, "Completed", "YES"),
("Shinka no Mi: Shiranai Uchi ni Kachigumi Jinsei", "The Fruit of Evolution: Before I Knew It, My Life Had It Made", 1, 12, "Completed", "YES"),
("Shinka no Mi: Shiranai Uchi ni Kachigumi Jinsei 2", "The Fruit of Evolution: Before I Knew It, My Life Had It Made 2", 2, 12, "Completed", "YES"),
("Fruit Basket (2019)", "Fruit Basket (2019)", 1, 25, "Completed", "YES"),
("Fruit Basket 2", "Fruit Basket 2", 2, 25, "Completed", "YES"),
("Fruits Basket: The Final", "Fruits Basket: The Final", 3, 13, "Completed", "YES"),
("Beastars", "Beastars", 1, 12, "Completed", "YES"),
("Beastars 2", "Beastars 2", 2, 12, "Completed", "YES"),
("Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru", "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat", 1, 12, "Completed", "YES"),
("Mieruko-chan", "Mieruko-chan", 1, 12, "Completed", "YES"),
("Tate no Yuusha no Nariagari 2", "The Rising of the Shield Hero 2", 2, 13, "Completed", "YES"),
("Shinigami Bocchan to Kuro Maid", "The Duke of Death and His Maid", 1, 12, "Completed", "YES"),
("Seirei Gensouki", "Spirit Chronicles", 1, 12, "Completed", "YES"),
("Uchi no Maid ga Uzasugiru!", "Uchi no Maid ga Uzasugiru!", 1, 12, "Completed", "YES"),
("Meikyuu Black Company", "The Dungeon of Black Company", 1, 12, "Completed", "YES"),
("Senpai ga Uzai Kouhai no Hanashi", "My Senpai is Annoying", 1, 12, "Completed", "YES"),
("Tsuki ga Michibiku Isekai Douchuu", "Moonlit Fantasy", 1, 12, "Completed", "YES"),
("Maoyuu Maou Yuusha", "Archenemy & Hero", 1, 12, "Completed", "YES"),
("Kiznaiver", "Kiznaiver", 1, 12, "Completed", "YES"),
("Gaikotsu Kishi-sama, Tadaima Isekai e Odekakuchuu", "Skeleton Knight in Another World", 1, 12, "Completed", "YES"),
("Dororo", "Dororo", 1, 26, "Completed", "YES"),
("Cheat Kusushi no Slow Life: Isekai ni Tsukurou Drugstore", "Drug Store in Another World - The Slow Life of a Cheat Pharmacist", 1, 12, "Completed", "YES"),
("Aharen-san wa Hakarenai", "Aharen-san wa Hakarenai", 1, 12, "Completed", "YES"),
("RWBY: Hyousetsu Teikoku", "RWBY: Ice Queendom", 1, 12, "Completed", "YES"),
("Kage no Jitsuryokusha ni Naritakute!", "Eminence in the Shadow", 1, 20, "Completed", "YES"),
("Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!", "No Matter How I Look At It, It's You Guys' Fault I'm Not Popular!", 1, 12, "Completed", "YES"),
("Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni shimashita", "Banished from the Hero’s Party, I Decided to Live a Quiet Life in the Countryside", 1, 13, "Completed", "YES"),
("Kenja no Deshi wo Nanoru Kenja", "She Professed Herself Pupil of the Wise Man", 1, 12, "Completed", "YES"),
("Orange", "Orange", 1, 13, "Completed", "YES"),
("Orange: Mirai", "Orange: Future", "MOVIE", 1, "Completed", "YES"),
("Mamahaha no Tsurego ga Motokano datta", "My Stepmom's Daughter is My Ex", 1, 12, "Completed", "YES"),
("Megami-ryou no Ryoubo-kun", "Mother of the Goddess Dormitory", 1, 10, "Completed", "YES"),
("Shadows House", "Shadows House", 1, 13, "Completed", "YES"),
("Shadows House 2", "Shadows House 2", 2, 12, "Completed", "YES"),
("Vivy: Fluorite Eye’s Song", "Fluorite Eye’s Song", 1, 13, "Completed", "YES"),
("Fantasy Bishoujo Juniku Oji-san to", "Life With an Ordinary Guy Who Reincarnated Into a Total Fantasy Knockout", 1, 12, "Completed", "YES"),
("Selection Project", "Selection Project", 1, 13, "Completed", "YES"),
("Conception", "Conception", 1, 12, "Completed", "YES"),
("Shijou Saikyou no Daimaou, Murabito A ni Tensei suru", "The Greatest Demon Lord Is Reborn as a Typical Nobody", 1, 12, "Completed", "YES"),
("Akebi-chan no Sailor Fuku", "Akebi-chan's Sailor Uniform", 1, 12, "Completed", "YES"),
("The God of High School", "The God of High School", 1, 13, "Completed", "YES"),
("Munou na Nana", "Talentless Nana", 1, 13, "Completed", "YES"),
("Ai no Utagoe wo Kikasete", "Sing a Bit of Harmony", "MOVIE", 1, "Completed", "YES"),
("Akatsuki no Yona", "Yona of the Dawn", 1, 24, "Completed", "YES"),
("Otomege Sekai wa Mob ni Kibishii Sekai desu", "Trapped in a Dating Sim: The World of Otome Games Is Tough for Mobs", 1, 12, "Completed", "YES"),
("Futoku no Guild", "Immoral Guild", 1, 12, "Completed", "YES"),
("Isekai Meikyuu de Harem wo", "Harem in the Labyrinth of Another World", 1, 12, "Completed", "YES"),
("Gakkougurashi!", "School-Live", 1, 12, "Completed", "YES"),
("Seijo no Maryoku wa Bannou desu", "The Saint's Magic Power is Omnipotent", 1, 12, "Completed", "YES"),
("Slow Start", "Slow Start", 1, 12, "Completed", "YES"),
("Amanchu!", "Amanchu!", 1, 12, "Completed", "YES"),
("Koi wa Ameagari no You ni", "After the Rain", 1, 12, "Completed", "YES"),
("Isekai Cheat Magician", "Isekai Cheat Magician", 1, 12, "Completed", "YES"),
("Oda Nobuna no Yabou", "The Ambition of Oda Nobuna", 1, 12, "Completed", "YES"),
("Special A", "Special A", 1, 24, "Completed", "YES"),
("Release the Spyce", "Release the Spyce", 1, 12, "Completed", "YES"),
("Yakusoku no Neverland", "Promise Neverland", 1, 12, "Completed", "YES"),
("Yakusoku no Neverland 2", "Promise Neverland 2", 2, 11, "Completed", "YES"),
("Ookami to Koushinryou", "Spice and Wolf", 1, 13, "Completed", "YES"),
("Ookami to Koushinryou II", "Spice and Wolf II", 2, 12, "Completed", "YES"),
("Tensei Shitara Slime Datta Ken: Guren no Kizuna-hen", "That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond", "MOVIE 3.1", 24, "Completed", "YES"),
("Eiyuu-ou, Bu wo Kiwameru Tame Tenseisu: Soshite, Sekai Saikyou no Minarai Kishi♀", "Reborn to Master the Blade From Hero-King to Extraordinary Squire", 1, 12, "Completed", "YES"),
("Tensei Oujo to Tensai Reijou no Mahou Kakumei", "The Magical Revolution of the Reincarnated Princess and the Genius Young Lady", 1, 12, "Completed", "YES"),
("Ningen Fushin no Boukensha-tachi ga Sekai wo Sukuu you desu", "Apparently, Disillusioned Adventurers Will Save the World", 1, 12, "Completed", "YES"),
("Koori Zokusei Danshi to Cool na Douryou Joshi", "The Ice Guy and His Cool Female Colleague", 1, 12, "Completed", "YES"),
("Paripi Koumei", "Ya Boy Kongming!", 1, 12, "Completed", "YES"),
("Summer Time Rendering", "Summer Time Rendering", 1, 25, "Completed", "YES"),
("Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen", "Ascendance of a Bookworm", 1, 14, "Completed", "YES"),
("Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 2", "Ascendance of a Bookworm 2", 2, 12, "Completed", "YES"),
("Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 3", "Ascendance of a Bookworm 3", 3, 10, "Completed", "YES"),
("Kakkou no Iinazuke", "A Couple of Cuckoos", 1, 24, "Completed", "YES"),
("Kuro no Keiyakusha", "Darker than Black", 1, 25, "Completed", "YES"),
("Ryuusei no Gemini", "Darker than Black: Gemini of the Meteor", 2, 12, "Completed", "YES"),
("Oshi ga Budoukan Ittekuretara Shinu", "If My Favorite Pop Idol Made It to the Budokan, I Would Die", 1, 12, "Completed", "YES"),
("Shokei Shoujo no Virgin Road;", "The Executioner and Her War of Life", 1, 12, "Completed", "YES"),
("Akuyaku Reijou nano de Last Boss wo Kattemimashita", "I'm the Villainess, So I'm Taming the Final Boss", 1, 12, "Completed", "YES"),
("Prima Doll", "Prima Doll", 1, 12, "Completed", "YES"),
("Noumin Kanren no Skill Bakka Agetetara Naze ka Tsuyoku Natta", "I've Somehow Gotten Stronger When I Improved My Farm-Related Skills", 1, 12, "Completed", "YES"),
("Kekkai Sensen", "Blood Blockade Battlefront", 1, 12, "Completed", "YES"),
("Kekkai Sensen & Beyond", "Blood Blockade Battlefront & Beyond", 2, 12, "Completed", "YES"),
("Engage Kiss", "Engage Kiss", 1, 13, "Completed", "YES"),
("Kemono Jihen", "Kemono Jihen", 1, 12, "Completed", "YES"),
("Boku ga Aishita Subete no Kimi e", "To Every You I’ve Loved Before", "MOVIE", 1, "Completed", "YES"),
("Kimi wo Aishita Hitori no Boku e", "To Me, The One Who Loved You", "MOVIE", 1, "Completed", "YES"),
("Isekai Shokudou", "Restaurant to Another World", 1, 12, "Completed", "YES"),
("Isekai Shokudou 2", "Restaurant to Another World 2", 2, 12, "Completed", "YES"),
("Koroshi Ai", "Love of Kill", 1, 12, "Completed", "YES"),
("Saikin Yatotta Maid ga Ayashii", "The Maid I Hired Recently is Mysterious", 1, 11, "Completed", "YES"),
("Sarazanmai", "Sarazanmai", 1, 11, "Completed", "YES"),
("Shiroi Suna no Aquatope", "The Aquatope on White Sand", 1, 24, "Completed", "YES"),
("Doukyuusei", "Classmates", "MOVIE", 1, "Completed", "YES"),
("Banana Fish", "Banana Fish", 1, 24, "Completed", "YES"),
("Tondemo Skill de Isekai Hourou Meshi", "Campfire Cooking in Another World with my Absurd Skill", 1, 12, "Completed", "YES"),
("Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai wo Tsuki Susumu", "Vermeil in Gold", 1, 12, "Completed", "YES"),
("Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu Sekai wo mo Musou Suru Level Up wa Jinsei wo Kaeta", "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too", 1, 13, "Completed", "YES"),
("Tsuki to Laika to Nosferatu", "Irina: The Vampire Cosmonaut", 1, 12, "Completed", "YES"),
("Durarara!!", "Durarara!!", 1, 24, "Completed", "YES"),
("Durarara X2", "Durarara!! X2", 2, 12, "Completed", "YES"),
("Durarara!! X2 The Second Arc", "Durarara!! X2 The Second Arc", 3, 12, "Completed", "YES"),
("Durarara!! X2 The Third Arc", "Durarara!! X2 The Third Arc", 4, 12, "Completed", "YES"),
("Asa Made Jugyo Chu", "See Me After Class", "OVA", 1, "Completed", "YES"),
("Isekai Oji-san", "Uncle from Another World", 1, 13, "Completed", "YES"),
("NANA", "NANA", 1, 47, "Completed", "YES"),
("Kubo-san wa Mob wo Yurusanai", "Kubo Won't Let Me Be Invisible", 1, 12, "Completed", "YES"),
("MASHLE: Kami Shinkakusha Kouho Senbatsu Shiken-hen", "Magic and Muscles", 1, 12, "Completed", "YES"),
("Heroine Tarumono!: Kiraware Heroine to Naisho no Oshigoto", "Heroines Run the Show", 1, 12, "Completed", "YES"),
("Onii-chan wa Oshimai!", "I'm Now Your Sister!", 1, 12, "Completed", "YES"),
("Saikyou Onmyouji no Isekai Tenseiki", "The Reincarnation of the Strongest Exorcist in the Another World", 1, 13, "Completed", "YES"),
("100-man no Inochi no Ue ni Ore wa Tatteiru", "I'm Standing on a Million Lives", 1, 12, "Completed", "YES"),
("100-man no Inochi no Ue ni Ore wa Tatteiru 2", "I'm Standing on a Million Lives 2", 2, 12, "Completed", "YES"),
("Tensei Shitara Ken Deshita", "Reincarnated as a Sword: I Became a Sword by Transmigrating", 1, 12, "Completed", "YES"),
("Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken", "The Angel Next Door Spoils Me Rotten", 1, 12, "Completed", "YES"),
("Tomodachi Game", "Tomodachi Game", 1, 12, "Completed", "YES"),
("Isekai Nonbiri Nouka", "Farming Life in Another World", 1, 12, "Completed", "YES"),
("Steins Gate (Ep 1 - 22)", "Steins;Gate", 1, 22, "Completed", "YES"),
("Steins Gate: Kyoukaimenjou no Missing Link", "Steins;Gate 0: 23β -Divide by Zero-", 2, 1, "Completed", "YES"),
("Steins Gate 0", "Steins Gate 0", 3, 23, "Completed", "YES"),
("Steins Gate (Ep 23 - 24)", "Steins;Gate", 4, 2, "Completed", "YES"),
("Steins;Gate: Oukoubakko no Poriomania", "Steins Gate: Egoistic Poriomania", 5, 1, "Completed", "YES"),
("Steins;Gate: Fuka Ryouiki no Déjà vu", "Steins;Gate The Movie – Load Region of Déjà Vu", "MOVIE", 1, "Completed", "YES"),
("Isekai Shoukan wa Nidome desu", "Summoned to Another World for a Second Time", 1, 12, "Completed", "YES"),
("Fate/Zero", "Fate/Zero", 2, 13, "Completed", "YES"),
("Fate/Zero 2", "Fate/Zero 2", 3, 12, "Completed", "YES"),
("Fate/Stay Night", "Fate/Stay Night", 1, 24, "Completed", "YES"),
("Fate/Stay Night: Unlimited Blade Works (Prologue)", "Fate/Stay Night: Unlimited Blade Works (Prologue)", "OVA 3.1", 1, "Completed", "YES"),
("Fate/Stay Night: Unlimited Blade Works", "Fate/Stay Night: Unlimited Blade Works", 4, 12, "Completed", "YES"),
("Fate/Stay Night: Unlimited Blade Works 2", "Fate/Stay Night: Unlimited Blade Works 2", 5, 13, "Completed", "YES"),
("Fate/Stay Night: Unlimited Blade Works 2 - Sunny Day", "Fate/Stay Night: Unlimited Blade Works 2 - Sunny Day", "OVA 5.1", 1, "Completed", "YES"),
("Fate/Stay Night: Heaven's Feel - I. Presage Flower", "Fate/Stay Night: Heaven's Feel - I. Presage Flower", "MOVIE 5.2", 1, "Completed", "YES"),
("Fate/Stay Night: Heaven's Feel - II. Lost Butterfly", "Fate/Stay Night: Heaven's Feel - II. Lost Butterfly", "MOVIE 5.3", 1, "Completed", "YES"),
("Fate/Stay Night: Heaven's Feel - III. Spring Song", "Fate/Stay Night: Heaven's Feel - III. Spring Song", "MOVIE 5.4", 1, "Completed", "YES"),
("Fate/kaleid liner Prisma Illya", "Fate/kaleid liner Prisma Illya", 6, 10, "Completed", "YES"),
("Fate/kaleid liner Prisma Illya 2wei!", "Fate/kaleid liner Prisma Illya 2wei!", 7, 10, "Completed", "YES"),
("Fate/kaleid liner Prisma Illya 2wei Herz!", "Fate/kaleid liner Prisma Illya 2wei Herz!", 8, 10, "Completed", "YES"),
("Fate/kaleid liner Prisma Illya 3rei!!", "Fate/kaleid liner Prisma Illya 3rei!!", 9, 12, "Completed", "YES"),
("Fate/kaleid liner Prisma Illya Movie: Oath Under Snow", "Fate/kaleid liner Prisma Illya Movie: Oath Under Snow", "MOVIE 9.1", 1, "Completed", "YES"),
("Fate/Apocrypha", "Fate/Apocrypha", 10, 25, "Completed", "YES"),
("Fate/Grand Order: First Order", "Fate/Grand Order: First Order", 1, 1, "Completed", "YES"),
("Fate/Grand Order: Moonlight Lostroom", "Fate/Grand Order: Moonlight Lostroom", "OVA", 1, "Completed", "YES"),
("Ijiranaide, Nagatoro-san 2nd Attack", "Don't Toy With Me, Miss Nagatoro 2nd Attack", 2, 12, "Completed", "YES"),
("Suzume no Tojimari", "Suzume no Tojimari", "MOVIE", 1, "Completed", "YES"),
("Hataraku Saibou!!", "Cells at Work!!", 2, 8, "Completed", "YES"),
("Overlord IV", "Overlord IV", 4, 13, "Completed", "YES"),
("Tonikaku Kawaii 2", "Over The Moon For You 2", 2, 12, "Completed", "YES"),
("Tonikaku Kawaii: Joshikou-hen", "Over The Moon For You ~High School Days~", "OVA 2", 4, "Completed", "YES"),
("Dr. Stone: Special Episode RYUSUI", "Dr. Stone: Special Episode RYUSUI", "MOVIE 2.1", 1, "Completed", "YES"),
("Dr. Stone: New World", "Dr. Stone: New World", 3, 11, "Completed", "YES"),
("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka IV Part 2", "Is It Wrong to Try to Pick Up Girls in a Dungeon? IV Part 2", 5, 11, "Completed", "YES"),
("Isekai wa Smartphone to Tomo ni 2", "In Another World With My Smartphone 2", 2, 12, "Completed", "YES"),
("Shuumatsu no Valkyrie II", "Records of Ragnarok II", 2, 10, "Completed", "YES"),
("Shuumatsu no Valkyrie II Part 2", "Records of Ragnarok II Part 2", 3, 5, "Completed", "YES"),
("Jigokuraku", "Hell's Paradise", 1, 13, "Completed", "YES"),
("Princess Connect! Re:Dive 2", "Princess Connect! Re:Dive 2", 2, 12, "Completed", "YES"),
("Yuusha ga Shinda!", "The Legendary Hero is Dead!", 1, 12, "Completed", "YES"),
("Kenja no Mago", "Wise Man’s Grandchild", 1, 12, "Completed", "YES"),
("Tomo-chan wa Onnanoko!", "Tomo-chan Is a Girl!", 1, 13, "Completed", "YES"),
("World Trigger", "World Trigger", 1, 73, "Completed", "YES"),
("World Trigger 2", "World Trigger 2", 2, 12, "Completed", "YES"),
("World Trigger 3", "World Trigger 3", 3, 14, "Completed", "YES"),
("Kono Oto Tomare!", "Kono Oto Tomare!: Sounds of Life", 1, 13, "Completed", "YES"),
("Kono Oto Tomare! 2", "Kono Oto Tomare!: Sounds of Life 2", 2, 13, "Completed", "YES"),
("Tengoku Daimakyou", "Heavenly Delusions", 1, 13, "Completed", "YES"),
("Deca-dence", "Deca-dence", 1, 12, "Completed", "YES"),
("Danshi Koukousei no Nichijou", "Daily Lives of High School Boys", 1, 12, "Completed", "YES"),
("Horimiya: piece", "Horimiya: The Missing Pieces", 1.2, 13, "Completed", "YES"),
("Level 1 dakedo Unique Skill de Saikyou desu", "My Unique Skill Makes Me OP even at Level 1", 1, 13, "Completed", "YES"),
("Jitsu wa Ore, Saikyou Deshita? (12)", "Am I Actually the Strongest?", 1, 12, "Completed", "YES"),
("Eiyuu Kyoushitsu", "Classroom for Heroes", 1, 12, "Completed", "YES"),
("Liar, Liar", "Liar, Liar", 1, 12, "Completed", "YES"),
("Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou II", "History’s Strongest Demon King Reincarnates and Goes to School with His Descendants II", 2, 12, "Completed", "YES"),
("Isekai Ittara Honki Dasu 2", "Jobless Reincarnation 2", 3, 12, "Completed", "YES"),
("Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu 2", "I Don't Want to Get Hurt, so I'll Max Out My Defense 2", 2, 12, "Completed", "YES"),
("Uchi no Kaisha no Chiisai Senpai no Hanashi", "My Tiny Senpai", 1, 12, "Completed", "YES"),
("R-15", "R-15", 1, 12, "Completed", "YES"),
("Natsu e no Tunnel, Sayonara no Deguchi", "The Tunnel to Summer, the Exit of Goodbyes", "MOVIE", 1, "Completed", "YES"),
("Densetsu no Yuusha no Densetsu", "The Legend of the Legendary Heroes", 1, 24, "Completed", "YES"),
("Shuumatsu Nani Shitemasu ka? Isogashii desu ka? Sukutte Moratte Ii desu ka?", "What are you doing at the end of the world? Are you busy? Will you save us?", 1, 12, "Completed", "YES"),
("Masamune-kun no Revenge R", "Masamune-kun's revenge R", 2, 12, "Completed", "YES"),
("Yamada-kun to Lv999 no Koi wo Suru", "My Love Story with Yamada-kun at Lv999", 1, 13, "Completed", "YES"),
("Kaminaki Sekai no Kamisama Katsudou", "Working for God in a Godless World", 1, 12, "Completed", "YES"),
("Cyberpunk: Edgerunners", "Cyberpunk: Edgerunners", 1, 10, "Completed", "YES"),
("Buddy Daddies", "Buddy Daddies", 1, 12, "Completed", "YES"),
("Uramichi Oniisan", "Life Lessons with Uramichi Oniisan", 1, 13, "Completed", "YES"),
("SSSS.Gridman", "SSSS.Gridman", 1, 12, "Completed", "YES"),
("Mahouka Koukou no Rettousei: Raihousha-hen", "The Irregular at Magic High School: Visitor Arc", 2, 13, "Completed", "YES"),
("Mahouka Koukou no Rettousei: Tsuioku-hen", "The Irregular at Magic High School: Reminiscence Arc", "MOVIE 2.1", 1, "Completed", "YES"),
("Hataraku Maou-sama! 2", "The Devil is a Part-Timer! 2", 2, 12, "Completed", "YES"),
("Hataraku Maou-sama! 2 Part 2", "The Devil is a Part-Timer! 2 Part 2", 3, 12, "Completed", "YES"),
("Isekai Yakkyoku", "Parallel World Pharmacy", 1, 12, "Completed", "YES"),
("Jidou Hanbaiki ni Umarekawatta Ore wa Meikyuu wo Samayou", "Reborn as a Vending Machine, I Now Wander the Dungeon", 1, 12, "Completed", "YES"),
("Suki na Ko ga Megane wo Wasureta", "The Girl I Like Forgot Her Glasses", 1, 13, "Completed", "YES"),
("SSSS.Dynazenon", "SSSS.Dynazenon", 2, 12, "Completed", "YES"),
("Gridman Universe", "Gridman Universe", "MOVIE", 1, "Completed", "YES"),
("Edomae Elf", "Otaku Elf", 1, 12, "Completed", "YES"),
("Last Period: Owarinaki Rasen no Monogatari", "Last Period: the journey to the end of the despair", 1, 12, "Completed", "YES"),
("Megami no Café Terrace", "The Café Terrace and Its Goddesses", 1, 12, "Completed", "YES"),
("Kokkoku", "Kokkoku", 1, 12, "Completed", "YES"),
("Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen", "Our Last Crusade or the Rise of a New World", 1, 12, "Completed", "YES"),
("Helck", "Helck", 1, 24, "Completed", "YES"),
("Kage no Jitsuryokusha ni Naritakute! 2", "Eminence in the Shadow 2", 2, 12, "Completed", "YES"),
("Jujutsu Kaisen 2", "Jujutsu Kaisen 2", 2, 23, "Completed", "YES"),
("Tsundere Akuyaku Reijou Liselotte to Jikkyou no Endou-kun to Kaisetsu no Kobayashi-san", "Endo and Kobayashi Live! The Latest on Tsundere Villainess Lieselotte", 1, 12, "Completed", "YES"),
("Benriya Saitou-san, Isekai ni Iku", "Handyman Saitou in Another World", 1, 12, "Completed", "YES"),
("Seiken Gakuin no Maken Tsukai", "The Demon Sword Master of Excalibur Academy", 1, 12, "Completed", "YES"),
("TenPuru", "Temple", 1, 12, "Completed", "YES"),
("Dr. Stone New World Part 2", "Dr. Stone New World Part 2", 4, 11, "Completed", "YES"),
("Magi: The Labyrinth of Magic", "Magi: The Labyrinth of Magic", 1, 25, "Completed", "YES"),
("Magi: The Kingdom of Magic", "Magi: The Kingdom of Magic", 2, 25, "Completed", "YES"),
("Magi: Adventure of Sinbad", "Magi: Adventure of Sinbad", 3, 13, "Completed", "YES"),
("Tensei Kizoku no Isekai Boukenroku: Jichou wo Shiranai Kamigami no Shito", "The Aristocrat’s Otherworldly Adventure: Serving Gods Who Go Too Far", 1, 12, "Completed", "YES"),
("Kuro no Shoukanshi", "Black Summoner", 1, 12, "Completed", "YES"),
("Hyouken no Majutsushi ga Sekai wo Suberu", "The Iceblade Sorcerer Shall Rule the World", 1, 12, "Completed", "YES"),
("Zom 100: Zombie ni Naru Made ni Shitai 100 no Koto", "Zom 100: Bucket List of the Dead", 1, 12, "Completed", "YES"),
("Kikansha no Mahou wa Tokubetsu desu", "A Returner's Magic Should Be Special", 1, 12, "Completed", "YES"),
("Potion-danomi de Ikinobimasu!", "I Shall Survive Using Potions!", 1, 12, "Completed", "YES"),
("Boukensha ni Naritai to Miyako ni Deteitta Musume ga S Rank ni Natteta", "My Daughter Left the Nest and Returned an S-Rank Adventurer", 1, 13, "Completed", "YES"),
("Shinmai Renkinjutsushi no Tenpo Keiei", "Management of a Novice Alchemist", 1, 12, "Completed", "YES"),
("Isekai One Turn Kill Nee-san: Ane Douhan no Isekai Seikatsu Hajimemashita", "My One-Hit Kill Sister", 1, 12, "Completed", "YES"),
("Re:Creators", "Re:Creators", 1, 22, "Completed", "YES"),
("Rougo ni Sonaete Isekai de 8-manmai no Kinka wo Tamemasu", "Saving 80,000 Gold in Another World for My Retirement", 1, 12, "Completed", "YES"),
("Toaru Ossan no VRMMO Katsudouki", "A Playthrough of a Certain Dude's VRMMO Life", 1, 12, "Completed", "YES"),
("Mairimashita! Iruma-kun", "Welcome to Demon School! Iruma-kun", 1, 23, "Completed", "YES"),
("Mairimashita! Iruma-kun 2", "Welcome to Demon School! Iruma-kun Season 2", 2, 21, "Completed", "YES"),
("Mairimashita! Iruma-kun 3", "Welcome to Demon School! Iruma-kun Season 3", 3, 21, "Completed", "YES"),
("Oshiete! Galko-chan", "Please tell me! Galko-chan", 1, 12, "Completed", "YES"),
("Watashi no Oshi wa Akuyaku Reijou.", "I'm in Love with the Villainess", 1, 12, "Completed", "YES"),
("Konyaku Haki sareta Reijou wo Hirotta Ore ga, Ikenai Koto wo Oshiekomu", "I'm Giving the Disgraced Noble Lady I Rescued a Crash Course in Naughtiness", 1, 12, "Completed", "YES"),
("Maou-sama, Retry!", "Demon Lord, Retry!", 1, 12, "Completed", "YES"),
("Skip to Loafer", "Skip and Loafer", 1, 12, "Completed", "YES"),
("Dekoboko Majo no Oyako Jijou", "The Family Circumstances of the Irregular Witch", 1, 12, "Completed", "YES"),
("Nanatsu no Maken ga Shihai Suru", "Reign of the Seven Spellblades", 1, 15, "Completed", "YES"),
("Kyokou Suiri", "In/Spectre", 1, 12, "Completed", "YES"),
("Kyokou Suiri 2", "In/Spectre 2", 2, 12, "Completed", "YES"),
("Buta no Liver wa Kanetsu Shiro", "Butareba -The Story of a Man Turned into a Pig-", 1, 12, "Completed", "YES"),
("Made in Abyss", "Made in Abyss", 1, 13, "Completed", "YES"),
("Made in Abyss: Dawn of the Deep Soul", "Made in Abyss: Dawn of the Deep Soul", "MOVIE 1.1", 1, "Completed", "YES"),
("Made in Abyss: Retsujitsu no Ougonkyou", "Made in Abyss: The Golden City of the Scorching Sun", 2, 12, "Completed", "YES"),
("Saikin, Imouto no Yousu ga Chotto Okashiinda ga", "Recently, My Sister Is Unusual", 1, 12, "Completed", "YES"),
("Kimi wa Houkago Insomnia", "Insomniacs after school", 1, 13, "Completed", "YES"),
("Kanojo ga Koushaku-tei ni Itta Riyuu", "Why Raeliana Ended Up at the Duke’s Mansion", 1, 12, "Completed", "YES"),
("Yuusha Party wo Tsuihou Sareta Beast Tamer, Saikyoushu no Nekomimi Shoujo to Deau", "Beast Tamer", 1, 13, "Completed", "YES"),
("Saihate no Paladin", "The Faraway Paladin", 1, 12, "Completed", "YES"),
("Keppeki Danshi! Aoyama-kun", "Clean Freak! Aoyama kun", 1, 12, "Completed", "YES"),
("Blue Lock", "Blue Lock", 1, 24, "Completed", "YES"),
("Arte", "Arte", 1, 12, "Completed", "YES"),
("Ura Sekai Picnic", "Otherside Picnic", 1, 12, "Completed", "YES"),
("Tate no Yuusha no Nariagari 3", "The Rising of the Shield Hero 3", 3, 12, "Completed", "YES"),
("Seijo no Maryoku wa Bannou desu 2", "The Saint's Magic Power is Omnipotent 2", 2, 12, "Completed", "YES"),
("Dark Gathering", "Dark Gathering", 1, 25, "Completed", "YES"),
("Sousou no Frieren", "Frieren: Beyond Journey’s End", 1, 28, "Completed", "YES"),
("Akuyaku Reijou Level 99: Watashi wa Ura Boss desu ga Maou de wa Arimasen", "Villainess Level 99: I May Be the Hidden Boss but I'm Not the Demon Lord", 1, 12, "Completed", "YES"),
("Sokushi Cheat ga Saikyou Sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga", "My Instant Death Ability is Overpowered", 1, 12, "Completed", "YES"),
("Mato Sehei no Slave", "Chained Soldier", 1, 12, "Completed", "YES"),
("Saijaku Teimā wa Gomihiroi no Tabi o Hajimemashita", "The Weakest Tamer Began a Journey to Pick Up Trash", 1, 12, "Completed", "YES"),
("Chiyu Mahō no Machigatta Tsukai-kata: Senjō o Kakeru Kaifuku Yōin", "The Wrong Way to Use Healing Magic", 1, 13, "Completed", "YES"),
("Undead Unluck", "Undead Unluck", 1, 24, "Completed", "YES"),
("Solo Leveling", "Solo Leveling", 1, 12, "Completed", "YES"),
("MASHLE: Kami Shinkakusha Kouho Senbatsu Shiken-hen", "Magic and Muscles Season 2", 2, 12, "Completed", "YES"),
("Oroka na Tenshi wa Akuma to Odoru", "The Foolish Angel Dances with the Devil", 1, 12, "Completed", "YES"),
("Okashi na Tensei", "Sweet Reincarnation", 1, 12, "Completed", "YES"),
("Yumemiru Danshi wa Genjitsushugisha", "The Dreaming Boy is a Realist", 1, 12, "Completed", "YES"),
("Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou Sareru", "The Strongest Tank's Labyrinth Raids -A Tank with a Rare 9999 Resistance Skill Got Kicked from the Hero's Party-", 1, 12, "Completed", "YES"),
("Kusuriya no Hitorigoto", "The Apothecary Diaries", 1, 24, "Completed", "YES"),
("Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni shimashita 2nd", "Banished from the Hero’s Party, I Decided to Live a Quiet Life in the Countryside Season 2", 2, 12, "Completed", "YES"),
("Boku no Kokoro no Yabai Yatsu", "The Dangers in My Heart", 1, 12, "Completed", "YES"),
("Boku no Kokoro no Yabai Yatsu Season 2", "The Dangers in My Heart Season 2", 2, 13, "Completed", "YES"),
("Kekkon Yubiwa Monogatari", "Tales of Wedding Rings", 1, 12, "Completed", "YES"),
("Ragna Crimson", "Ragna Crimson", 1, 24, "Completed", "YES"),
("Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo", "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You", 1, 12, "Completed", "YES"),
("Tearmoon Teikoku Monogatari: Dantoudai kara Hajimaru, Hime no Tensei Gyakuten Story", "Tearmoon Empire", 1, 12, "Completed", "YES"),
("Loop 7-kaime no Akuyaku Reijou wa, Moto Tekikoku de Jiyuu Kimamana Hanayome Seikatsu wo Mankitsu Suru", "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!", 1, 12, "Completed", "YES"),
("Nozomanu Fushi no Boukensha", "The Unwanted Undead Adventurer", 1, 12, "Completed", "YES"),
("Keikenzumi na Kimi to, Keiken Zero na Ore ga, Otsukiai suru Hanashi", "Our Dating Story: The Experienced You and The Inexperienced Me", 1, 12, "Completed", "YES"),
("Hikikomari Kyuuketsuki no Monmon", "The Vexations of a Shut-In Vampire Princess", 1, 12, "Completed", "YES"),
("Dekiru Neko wa Kyou mo Yuuutsu", "The Masterful Cat is Depressed Again Today", 1, 13, "Completed", "YES"),
("Higeki no Genkyou to Naru Saikyou Gedou Last Boss Joou wa Tami no Tame ni Tsukushimasu", "The Most Heretical Last Boss Queen: From Villainess to Savior", 1, 12, "Completed", "YES"),
("Seija Musou: Salaryman, Isekai de Ikinokoru Tame ni Ayumu Michi", "The Great Cleric", 1, 12, "Completed", "YES"),
("Ishura", "Ishura", 1, 12, "Completed", "YES"),
("Kaiko sareta Ankoku Heishi (30-dai) no Slow na Second Life", "Chillin’ in My 30s after Getting Fired from the Demon King’s Army", 1, 12, "Completed", "YES"),
("Momochi-san Chi no Ayakashi Ouji", "The Demon Prince of Momochi House", 1, 12, "Completed", "YES"),
("Hime-sama, 'Goumon' no Jikan desu", "Tis Time for 'Torture,' Princess", 1, 12, "Completed", "YES"),
("Kamitachi ni Hirowareta Otoko", "By the Grace of the Gods", 1, 12, "Completed", "YES"),
("Kamitachi ni Hirowareta Otoko 2", "By the Grace of the Gods 2", 2, 12, "Completed", "YES"),
("Shichisei no Subaru", "Seven Senses of the Re'Union", 1, 12, "Completed", "YES"),
("Leadale no Daichi nite", "In the Land of Leadale", 1, 12, "Completed", "YES"),
("Knight's & Magic", "Knight's & Magic", 1, 13, "Completed", "YES"),
("Sasaki to Pii-chan", "Sasaki and Peeps", 1, 12, "Completed", "YES"),
("Spy x Family Season 2", "Spy x Family Season 2", 3, 12, "Completed", "YES"),
("Metallic Rouge", "Metallic Rouge", 1, 13, "Completed", "YES"),
("Jieitai Kanochi nite, Kaku Tatakaeri", "Gate", 1, 12, "Completed", "YES"),
("Jieitai Kanochi nite, Kaku Tatakaeri 2", "Gate 2", 2, 12, "Completed", "YES"),
("Haikyuu!!", "Haikyuu!!", 1, 25, "Completed", "YES"),
("Haikyuu!! 2nd Season", "Haikyuu!! 2nd Season", 2, 25, "Completed", "YES"),
("Haikyuu!!: Owari to Hajimari", "Haikyu!! the Movie: The End and the Beginning", "MOVIE", 1, "Completed", "YES"),
("Haikyuu!!: Shousha to Haisha", "Haikyuu!! the Movie: The Winner and the Loser", "MOVIE", 1, "Completed", "YES"),
("Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou", "Haikyuu!! 3rd Season", 3, 10, "Completed", "YES"),
("Haikyuu!!: Sainou to Sense", "Haikyu!! The Movie: Talent and Sense", "MOVIE", 1, "Completed", "YES"),
("Haikyuu!!: Concept no Tatakai", "Haikyu!! The Movie: Battle of Concepts", "MOVIE", 1, "Completed", "YES"),
("Haikyuu!! TO THE TOP", "Haikyuu!! TO THE TOP", 4, 13, "Completed", "YES"),
("Haikyuu!! TO THE TOP 2", "Haikyuu!! TO THE TOP 2", 5, 12, "Completed", "YES"),
("Maou-jou de Oyasumi", "Sleepy Princess in the Demon Castle", 1, 12, "Completed", "YES"),
("Ryza no Atelier: Tokoyami no Joou to Himitsu no Kakurega", "Atelier Ryza: Ever Darkness & the Secret Hideout The Animation", 1, 12, "Completed", "YES"),
("Mahou Shoujo ni Akogarete", "Gushing Over Magical Girls", 1, 13, "Completed", "YES"),
("Kamierabi", "KamiErabi GOD.app", 1, 12, "Completed", "YES"),
("ID: Invaded", "ID: Invaded", 1, 13, "Completed", "YES"),
("Dekisokonai to Yobareta Moto Eiyuu wa, Jikka kara Tsuihou Sareta node Suki Katte ni Ikiru Koto ni Shita", "The Banished Former Hero Lives as He Pleases", 1, 12, "Completed", "YES"),
("Jii-san Baa-san Wakagaeru", "Grandpa and Grandma Turn Young Again", 1, 11, "Completed", "YES"),
("Tensei Shitara Dai Nana Ouji Dattanode, Kimamani Majutsu wo Kiwamemasu", "I Was Reincarnated as the 7th Prince So I Can Take My Time Perfecting My Magical Ability", 1, 12, "Completed", "YES"),
("Lv2 Kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life", "Chillin' in Another World with Level 2 Super Cheat Powers", 1, 12, "Completed", "YES"),
("Re:Monster", "Re:Monster", 1, 12, "Completed", "YES"),
("Tsuki ga Michibiku Isekai Douchuu 2", "Moonlit Fantasy 2", 2, 25, "Completed", "YES"),
("Tensei Kizoku, Kantei Skill de Nariagaru: Jakushou Ryouchi wo Uketsuida node, Yuushuu na Jinzai wo Fuyashiteitara, Saikyou Ryouchi ni Natteta", "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World", 1, 12, "Completed", "YES"),
("Kono Subarashii Sekai ni Shukufuku wo! 3", "God's Blessing on This Wonderful World! 3", 3, 11, "Completed", "YES"),
("Kami wa Game ni Ueteiru", "Gods' Games We Play", 1, 13, "Completed", "YES"),
("Spy Kyoushitsu", "Spy Classroom", 1, 12, "Completed", "YES"),
("Spy Kyoushitsu 2", "Spy Classroom 2", 2, 12, "Completed", "YES"),
("Henjin no Salad Bowl", "A Salad Bowl of Eccentrics", 1, 12, "Completed", "YES"),
("Mahouka Koukou no Rettousei 3rd Season", "The Irregular at Magic High School Season 3", 3, 13, "Completed", "YES"),
("Seiyuu Radio no Uraomote", "The Many Sides of Voice Actor Radio", 1, 12, "Completed", "YES"),
("Dungeon Meshi", "Delicious in Dungeon", 1, 24, "Completed", "YES"),
("Log Horizon", "Log Horizon", 1, 25, "Completed", "YES"),
("Log Horizon 2", "Log Horizon 2", 2, 25, "Completed", "YES"),
("Log Horizon: Entaku Houkai", "Log Horizon: Destruction of the Round Table", 3, 12, "Completed", "YES"),
("Shuumatsu Train Doko e Iku?", "Train to the End of the World", 1, 12, "Completed", "YES"),
("Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?", "An Archdemon's Dilemma: How to Love Your Elf Bride", 1, 12, "Completed", "YES"),
("Unnamed Memory", "Unnamed Memory", 1, 12, "Completed", "YES"),
("BUCCHIGIRI?!", "BUCCHIGIRI?!", 1, 12, "Completed", "YES"),
("Koukaku no Pandora", "Pandora in the Crimson Shell Ghost Urn", 1, 12, "Completed", "YES"),
("Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou II Part 2", "The Misfit of Demon King Academy II (Cour 2)", 3, 12, "Completed", "YES"),
("The New Gate", "The New Gate", 1, 12, "Completed", "YES"),
("Isekai Ittara Honki Dasu 2 Part 2", "Jobless Reincarnation 2 Part 2", 4, 12, "Completed", "YES"),
("Isekai de Mofumofu Nadenade suru Tame ni Ganbattemasu.Isekai de Mofumofu Nadenade suru Tame ni Ganbattemasu.", "Fluffy Paradise", 1, 12, "Completed", "YES"),
("Jaku-Chara Tomozaki-kun", "Bottom-Tier Character Tomozaki", 1, 12, "Completed", "YES"),
("Jaku-Chara Tomozaki-kun 2nd Stage", "Bottom-Tier Character Tomozaki 2nd Stage", 2, 13, "Completed", "YES"),
("One Room, Hiatari Futsuu, Tenshi-tsuki", "Studio Apartment, Good Lighting, Angel Included", 1, 12, "Completed", "YES"),
("Net-juu no Susume", "Recovery of an MMO Junkie", 1, 10, "Completed", "YES"),
("Net-juu no Susume Special", "Recovery of an MMO Junkie Special", "OVA 1.1", 1, "Completed", "YES"),
("Accel World", "Accel World", 1, 24, "Completed", "YES"),
("Accel World EX", "Accel World EX", "OVA 1", 2, "Completed", "YES"),
("Accel World: Infinite∞Burst", "Accel World: Infinite∞Burst", "MOVIE 1.1", 1, "Completed", "YES"),
("Level 1 Maou and One Room Yuusha", "Level 1 Demon Lord and One Room Hero", 1, 12, "Completed", "YES"),
("Soredemo Sekai wa Utsukushii", "The World is Still Beautiful", 1, 12, "Completed", "YES"),
("Boushoku no Berserk", "Berserk of Gluttony", 1, 12, "Completed", "YES"),
("Isekai Suicide Squad", "Isekai Suicide Squad", 1, 10, "Completed", "YES"),
("Kaii to Otome to Kamikakushi", "Mysterious Disappearance", 1, 12, "Completed", "YES"),
("Sentai Daishikkaku", "Go go Go! Go! Loser Ranger!", 1, 12, "Completed", "YES"),
("Wind Breaker", "Wind Breaker", 1, 13, "Completed", "YES"),
("Blue Archive The Animation", "Blue Archive The Animation", 1, 12, "Completed", "YES"),
("Pon no Michi", "The Way of Pon", 1, 12, "Completed", "YES"),
("Dosanko Gal wa Namara Menkoi", "Hokkaido Gals Are Super Adorable!", 1, 12, "Completed", "YES"),
("Synduality Noir", "Synduality Noir", 1, 12, "Completed", "YES"),
("Synduality Noir Part 2", "Synduality Noir Part 2", 2, 12, "Completed", "YES"),
("Hametsu no Oukoku", "The Kingdoms of Ruin", 1, 12, "Completed", "YES"),
("Boukyaku Battery", "Oblivion Battery", 1, 12, "Completed", "YES"),
("Ramen Daisuki Koizumi-sanRamen Daisuki Koizumi-san", "Ms. Koizumi Loves Ramen Noodles", 1, 12, "Completed", "YES"),
("Deatte 5-byou de BattleDeatte 5-byou de Battle", "Battle Game in 5 Seconds", 1, 12, "Completed", "YES"),
("Shoshimin Series", "How to Become Ordinary", 1, 10, "Completed", "YES"),
("Shikanoko Nokonoko Koshitantan", "My Deer Friend Nokotan", 1, 12, "Completed", "YES"),
("Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu", "A Journey Through Another World: Raising Kids While Adventuring", 1, 12, "Completed", "YES"),
("Ore wa Subete wo 'Parry' suru: Gyaku Kanchigai no Sekai Saikyou wa Boukensha ni Naritai", "I Parry Everything: What Do You Mean I'm the Strongest? I'm Not Even an Adventurer Yet!", 1, 12, "Completed", "YES"),
("Maougun Saikyou no Majutsushi wa Ningen datta", "The Strongest Magician in the Demon Lord’s Army was a Human", 1, 12, "Completed", "YES"),
("Bye Bye, Earth", "Bye Bye, Earth", 1, 10, "Completed", "YES"),
("Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san", "Alya Sometimes Hides Her Feelings in Russian", 1, 12, "Completed", "YES"),
("Shinmai Ossan Bokensha, Saikyo Party ni Shinu Hodo Kitaerarete Muteki ni Naru", "The Ossan Newbie Adventurer, Trained to Death by the Most Powerful Party, Became Invincible", 1, 12, "Completed", "YES"),
("Madogushi Dariya wa Utsumukanai: Kyo kara Jiyu na Shokunin Raifu", "Dahlia in Bloom", 1, 12, "Completed", "YES"),
("Tsue to Tsurugi no Wistoria", "Wistoria: Wand and Sword", 1, 12, "Completed", "YES"),
("Tensei Shitara Slime Datta Ken 3rd Season", "That Time I Got Reincarnated as a Slime Part III", 4, 24, "Completed", "YES"),
("Hazurewaku no 'Joutai Ijou Skill' de Saikyou ni Natta Ore ga Subete wo Juurin suru made", "Failure Frame: I Became the Strongest and Annihilated Everything With Low-Level Spells", 1, 12, "Completed", "YES"),
("Naze Boku no Sekai wo Daremo Oboeteinai no ka?", "Why Does Nobody Remember Me in This World?", 1, 12, "Completed", "YES"),
("Mob kara Hajimaru Tansaku Eiyuutan", "A Nobodys Way Up An Exploration Hero", 1, 12, "Completed", "YES"),
("Yozakura-san Chi no Daisakusen", "Mission: Yozakura Family", 1, 27, "Completed", "YES"),
("Isekai Shikkaku", "No Longer Allowed in Another World", 1, 12, "Completed", "YES"),
("VTuber Nandaga Haishin Kiri Wasuretara Densetsu ni Natteta", "VTuber Legend: How I Went Viral after Forgetting to Turn Off My Stream", 1, 12, "Completed", "YES"),
("Kono Sekai wa Fukanzen Sugiru", "Quality Assurance in Another World", 1, 13, "Completed", "YES"),
("Make Heroine ga Oosugiru!", "Too Many Losing Heroines", 1, 12, "Completed", "YES"),
("Giji Harem", "Pseudo Harem", 1, 12, "Completed", "YES"),
("Spy x Family Movie", "Spy x Family Movie", "MOVIE 3.1", 1, "Completed", "YES"),
("Oshi no Ko", "My Star", 1, 11, "Completed", "YES"),
("Oshi no Ko Season 2", "My Star Season 2", 2, 13, "Completed", "YES"),
("Senpai is An Otokonoko", "My Crossdressing Senpai", 1, 12, "Completed", "YES"),
("Dungeon no Naka no Hito", "Dungeon People", 1, 12, "Completed", "YES"),
("Hananoi-kun to Koi no Yamai", "A Condition Called Love", 1, 12, "Completed", "YES"),
("Haikyuu!! Gomi Suteba no Kessen", "Haikyuu!! Movie: Battle of the Garbage Dump", "MOVIE", 1, "Completed", "YES"),
("Shy", "Shy", 1, 12, "Completed", "YES"),
("Shy Season 2", "Shy Season 2", 2, 12, "Completed", "YES"),
("Fairy Tail: 100-nen Quest", "Fairy Tail: 100 Year Quest", 2, 25, "Completed", "YES"),
("Monogatari Series: Off & Monster Season", "Monogatari Series: Off & Monster Season", 14, 14, "Completed", "YES"),
("Dandadan", "Dandadan", 1, 12, "Completed", "YES"),
("Jashin-chan Dropkick X", "Dropkick On My Devil!! X", 3, 12, "Completed", "YES"),
("Shokugyou de Sekai Saikyou 3", "From Commonplace to World's Strongest 3", 3, 16, "Completed", "YES");